#ifndef IL_DECODER_H
#define IL_DECODER_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// CIL Opcode enumeration
typedef enum {
    // Special instructions
    CIL_OPCODE_NOP = 0x00,
    CIL_OPCODE_BREAK = 0x01,
    
    // Load constants
    CIL_OPCODE_LDARG_0 = 0x02,
    CIL_OPCODE_LDARG_1 = 0x03,
    CIL_OPCODE_LDARG_2 = 0x04,
    CIL_OPCODE_LDARG_3 = 0x05,
    CIL_OPCODE_LDLOC_0 = 0x06,
    CIL_OPCODE_LDLOC_1 = 0x07,
    CIL_OPCODE_LDLOC_2 = 0x08,
    CIL_OPCODE_LDLOC_3 = 0x09,
    CIL_OPCODE_STLOC_0 = 0x0A,
    CIL_OPCODE_STLOC_1 = 0x0B,
    CIL_OPCODE_STLOC_2 = 0x0C,
    CIL_OPCODE_STLOC_3 = 0x0D,
    CIL_OPCODE_LDARG_S = 0x0E,
    CIL_OPCODE_LDARGA_S = 0x0F,
    CIL_OPCODE_STARG_S = 0x10,
    CIL_OPCODE_LDLOC_S = 0x11,
    CIL_OPCODE_LDLOCA_S = 0x12,
    CIL_OPCODE_STLOC_S = 0x13,
    CIL_OPCODE_LDNULL = 0x14,
    CIL_OPCODE_LDC_I4_M1 = 0x15,
    CIL_OPCODE_LDC_I4_0 = 0x16,
    CIL_OPCODE_LDC_I4_1 = 0x17,
    CIL_OPCODE_LDC_I4_2 = 0x18,
    CIL_OPCODE_LDC_I4_3 = 0x19,
    CIL_OPCODE_LDC_I4_4 = 0x1A,
    CIL_OPCODE_LDC_I4_5 = 0x1B,
    CIL_OPCODE_LDC_I4_6 = 0x1C,
    CIL_OPCODE_LDC_I4_7 = 0x1D,
    CIL_OPCODE_LDC_I4_8 = 0x1E,
    CIL_OPCODE_LDC_I4_S = 0x1F,
    CIL_OPCODE_LDC_I4 = 0x20,
    CIL_OPCODE_LDC_I8 = 0x21,
    CIL_OPCODE_LDC_R4 = 0x22,
    CIL_OPCODE_LDC_R8 = 0x23,
    CIL_OPCODE_UNUSED_49 = 0x24,
    CIL_OPCODE_DUP = 0x25,
    CIL_OPCODE_POP = 0x26,
    CIL_OPCODE_JMP = 0x27,
    CIL_OPCODE_CALL = 0x28,
    CIL_OPCODE_CALLI = 0x29,
    CIL_OPCODE_RET = 0x2A,
    CIL_OPCODE_BR_S = 0x2B,
    CIL_OPCODE_BRFALSE_S = 0x2C,
    CIL_OPCODE_BRTRUE_S = 0x2D,
    CIL_OPCODE_BEQ_S = 0x2E,
    CIL_OPCODE_BGE_S = 0x2F,
    CIL_OPCODE_BGT_S = 0x30,
    CIL_OPCODE_BLE_S = 0x31,
    CIL_OPCODE_BLT_S = 0x32,
    CIL_OPCODE_BNE_UN_S = 0x33,
    CIL_OPCODE_BGE_UN_S = 0x34,
    CIL_OPCODE_BGT_UN_S = 0x35,
    CIL_OPCODE_BLE_UN_S = 0x36,
    CIL_OPCODE_BLT_UN_S = 0x37,
    CIL_OPCODE_BR = 0x38,
    CIL_OPCODE_BRFALSE = 0x39,
    CIL_OPCODE_BRTRUE = 0x3A,
    CIL_OPCODE_BEQ = 0x3B,
    CIL_OPCODE_BGE = 0x3C,
    CIL_OPCODE_BGT = 0x3D,
    CIL_OPCODE_BLE = 0x3E,
    CIL_OPCODE_BLT = 0x3F,
    CIL_OPCODE_BNE_UN = 0x40,
    CIL_OPCODE_BGE_UN = 0x41,
    CIL_OPCODE_BGT_UN = 0x42,
    CIL_OPCODE_BLE_UN = 0x43,
    CIL_OPCODE_BLT_UN = 0x44,
    CIL_OPCODE_SWITCH = 0x45,
    CIL_OPCODE_LDIND_I1 = 0x46,
    CIL_OPCODE_LDIND_U1 = 0x47,
    CIL_OPCODE_LDIND_I2 = 0x48,
    CIL_OPCODE_LDIND_U2 = 0x49,
    CIL_OPCODE_LDIND_I4 = 0x4A,
    CIL_OPCODE_LDIND_U4 = 0x4B,
    CIL_OPCODE_LDIND_I8 = 0x4C,
    CIL_OPCODE_LDIND_I = 0x4D,
    CIL_OPCODE_LDIND_R4 = 0x4E,
    CIL_OPCODE_LDIND_R8 = 0x4F,
    CIL_OPCODE_LDIND_REF = 0x50,
    CIL_OPCODE_STIND_REF = 0x51,
    CIL_OPCODE_STIND_I1 = 0x52,
    CIL_OPCODE_STIND_I2 = 0x53,
    CIL_OPCODE_STIND_I4 = 0x54,
    CIL_OPCODE_STIND_I8 = 0x55,
    CIL_OPCODE_STIND_R4 = 0x56,
    CIL_OPCODE_STIND_R8 = 0x57,
    CIL_OPCODE_ADD = 0x58,
    CIL_OPCODE_SUB = 0x59,
    CIL_OPCODE_MUL = 0x5A,
    CIL_OPCODE_DIV = 0x5B,
    CIL_OPCODE_DIV_UN = 0x5C,
    CIL_OPCODE_REM = 0x5D,
    CIL_OPCODE_REM_UN = 0x5E,
    CIL_OPCODE_AND = 0x5F,
    CIL_OPCODE_OR = 0x60,
    CIL_OPCODE_XOR = 0x61,
    CIL_OPCODE_SHL = 0x62,
    CIL_OPCODE_SHR = 0x63,
    CIL_OPCODE_SHR_UN = 0x64,
    CIL_OPCODE_NEG = 0x65,
    CIL_OPCODE_NOT = 0x66,
    CIL_OPCODE_CONV_I1 = 0x67,
    CIL_OPCODE_CONV_I2 = 0x68,
    CIL_OPCODE_CONV_I4 = 0x69,
    CIL_OPCODE_CONV_I8 = 0x6A,
    CIL_OPCODE_CONV_R4 = 0x6B,
    CIL_OPCODE_CONV_R8 = 0x6C,
    CIL_OPCODE_CONV_U4 = 0x6D,
    CIL_OPCODE_CONV_U8 = 0x6E,
    CIL_OPCODE_CALLVIRT = 0x6F,
    CIL_OPCODE_CPOBJ = 0x70,
    CIL_OPCODE_LDOBJ = 0x71,
    CIL_OPCODE_LDSTR = 0x72,
    CIL_OPCODE_NEWOBJ = 0x73,
    CIL_OPCODE_CASTCLASS = 0x74,
    CIL_OPCODE_ISINST = 0x75,
    CIL_OPCODE_CONV_R_UN = 0x76,
    CIL_OPCODE_UNUSED_58 = 0x77,
    CIL_OPCODE_UNUSED_1 = 0x78,
    CIL_OPCODE_UNBOX = 0x79,
    CIL_OPCODE_THROW = 0x7A,
    CIL_OPCODE_LDFLD = 0x7B,
    CIL_OPCODE_LDFLDA = 0x7C,
    CIL_OPCODE_STFLD = 0x7D,
    CIL_OPCODE_LDSFLD = 0x7E,
    CIL_OPCODE_LDSFLDA = 0x7F,
    CIL_OPCODE_STSFLD = 0x80,
    CIL_OPCODE_STOBJ = 0x81,
    CIL_OPCODE_CONV_OVF_I1_UN = 0x82,
    CIL_OPCODE_CONV_OVF_I2_UN = 0x83,
    CIL_OPCODE_CONV_OVF_I4_UN = 0x84,
    CIL_OPCODE_CONV_OVF_I8_UN = 0x85,
    CIL_OPCODE_CONV_OVF_U1_UN = 0x86,
    CIL_OPCODE_CONV_OVF_U2_UN = 0x87,
    CIL_OPCODE_CONV_OVF_U4_UN = 0x88,
    CIL_OPCODE_CONV_OVF_U8_UN = 0x89,
    CIL_OPCODE_CONV_OVF_I_UN = 0x8A,
    CIL_OPCODE_CONV_OVF_U_UN = 0x8B,
    CIL_OPCODE_BOX = 0x8C,
    CIL_OPCODE_NEWARR = 0x8D,
    CIL_OPCODE_LDLEN = 0x8E,
    CIL_OPCODE_LDELEMA = 0x8F,
    CIL_OPCODE_LDELEM_I1 = 0x90,
    CIL_OPCODE_LDELEM_U1 = 0x91,
    CIL_OPCODE_LDELEM_I2 = 0x92,
    CIL_OPCODE_LDELEM_U2 = 0x93,
    CIL_OPCODE_LDELEM_I4 = 0x94,
    CIL_OPCODE_LDELEM_U4 = 0x95,
    CIL_OPCODE_LDELEM_I8 = 0x96,
    CIL_OPCODE_LDELEM_I = 0x97,
    CIL_OPCODE_LDELEM_R4 = 0x98,
    CIL_OPCODE_LDELEM_R8 = 0x99,
    CIL_OPCODE_LDELEM_REF = 0x9A,
    CIL_OPCODE_STELEM_I = 0x9B,
    CIL_OPCODE_STELEM_I1 = 0x9C,
    CIL_OPCODE_STELEM_I2 = 0x9D,
    CIL_OPCODE_STELEM_I4 = 0x9E,
    CIL_OPCODE_STELEM_I8 = 0x9F,
    CIL_OPCODE_STELEM_R4 = 0xA0,
    CIL_OPCODE_STELEM_R8 = 0xA1,
    CIL_OPCODE_STELEM_REF = 0xA2,
    CIL_OPCODE_LDELEM_ANY = 0xA3,
    CIL_OPCODE_STELEM_ANY = 0xA4,
    CIL_OPCODE_UNBOX_ANY = 0xA5,
    CIL_OPCODE_UNUSED_59 = 0xA6,
    CIL_OPCODE_UNUSED_60 = 0xA7,
    CIL_OPCODE_UNUSED_61 = 0xA8,
    CIL_OPCODE_UNUSED_62 = 0xA9,
    CIL_OPCODE_UNUSED_63 = 0xAA,
    CIL_OPCODE_UNUSED_64 = 0xAB,
    CIL_OPCODE_UNUSED_65 = 0xAC,
    CIL_OPCODE_UNUSED_66 = 0xAD,
    CIL_OPCODE_UNUSED_67 = 0xAE,
    CIL_OPCODE_CONV_OVF_I1 = 0xB3,
    CIL_OPCODE_CONV_OVF_U1 = 0xB4,
    CIL_OPCODE_CONV_OVF_I2 = 0xB5,
    CIL_OPCODE_CONV_OVF_U2 = 0xB6,
    CIL_OPCODE_CONV_OVF_I4 = 0xB7,
    CIL_OPCODE_CONV_OVF_U4 = 0xB8,
    CIL_OPCODE_CONV_OVF_I8 = 0xB9,
    CIL_OPCODE_CONV_OVF_U8 = 0xBA,
    CIL_OPCODE_UNUSED_50 = 0xC2,
    CIL_OPCODE_UNUSED_51 = 0xC3,
    CIL_OPCODE_UNUSED_52 = 0xC4,
    CIL_OPCODE_UNUSED_53 = 0xC5,
    CIL_OPCODE_UNUSED_54 = 0xC6,
    CIL_OPCODE_UNUSED_78 = 0xF5,
    CIL_OPCODE_UNUSED_79 = 0xF6,
    CIL_OPCODE_UNUSED_80 = 0xF7,
    CIL_OPCODE_UNUSED_81 = 0xF8,
    CIL_OPCODE_UNUSED_82 = 0xF9,
    CIL_OPCODE_UNUSED_83 = 0xFA,
    CIL_OPCODE_UNUSED_84 = 0xFB,
    CIL_OPCODE_UNUSED_85 = 0xFC,
    CIL_OPCODE_UNUSED_86 = 0xFD,
    CIL_OPCODE_UNUSED_87 = 0xFE,
    CIL_OPCODE_UNUSED_88 = 0xFF,
    
    // Extended opcodes (2-byte opcodes starting with 0xFE)
    CIL_OPCODE_ARGLIST = 0x100,
    CIL_OPCODE_CEQ = 0x101,
    CIL_OPCODE_CGT = 0x102,
    CIL_OPCODE_CGT_UN = 0x103,
    CIL_OPCODE_CLT = 0x104,
    CIL_OPCODE_CLT_UN = 0x105,
    CIL_OPCODE_LDFTN = 0x106,
    CIL_OPCODE_LDVIRTFTN = 0x107,
    CIL_OPCODE_UNUSED_56 = 0x108,
    CIL_OPCODE_LDARG = 0x109,
    CIL_OPCODE_LDARGA = 0x10A,
    CIL_OPCODE_STARG = 0x10B,
    CIL_OPCODE_LDLOC = 0x10C,
    CIL_OPCODE_LDLOCA = 0x10D,
    CIL_OPCODE_STLOC = 0x10E,
    CIL_OPCODE_LOCALLOC = 0x10F,
    CIL_OPCODE_UNUSED_57 = 0x110,
    CIL_OPCODE_ENDFILTER = 0x111,
    CIL_OPCODE_UNALIGNED = 0x112,
    CIL_OPCODE_VOLATILE = 0x113,
    CIL_OPCODE_TAIL = 0x114,
    CIL_OPCODE_INITOBJ = 0x115,
    CIL_OPCODE_CONSTRAINED = 0x116,
    CIL_OPCODE_CPBLK = 0x117,
    CIL_OPCODE_INITBLK = 0x118,
    CIL_OPCODE_UNUSED_69 = 0x119,
    CIL_OPCODE_RETHROW = 0x11A,
    CIL_OPCODE_UNUSED_55 = 0x11B,
    CIL_OPCODE_SIZEOF = 0x11C,
    CIL_OPCODE_REFANYTYPE = 0x11D,
    CIL_OPCODE_READONLY = 0x11E,
    CIL_OPCODE_UNUSED_89 = 0x11F,
    CIL_OPCODE_UNUSED_90 = 0x120,
    CIL_OPCODE_UNUSED_91 = 0x121,
    CIL_OPCODE_UNUSED_92 = 0x122,
    CIL_OPCODE_UNUSED_93 = 0x123,
    CIL_OPCODE_UNUSED_94 = 0x124,
    CIL_OPCODE_UNUSED_95 = 0x125,
    CIL_OPCODE_UNUSED_96 = 0x126,
    CIL_OPCODE_UNUSED_97 = 0x127,
    CIL_OPCODE_UNUSED_98 = 0x128,
    CIL_OPCODE_UNUSED_99 = 0x129,
    CIL_OPCODE_UNUSED_100 = 0x12A,
    CIL_OPCODE_UNUSED_101 = 0x12B,
    CIL_OPCODE_UNUSED_102 = 0x12C,
    CIL_OPCODE_UNUSED_103 = 0x12D,
    CIL_OPCODE_UNUSED_104 = 0x12E,
    CIL_OPCODE_UNUSED_105 = 0x12F,
    CIL_OPCODE_UNUSED_106 = 0x130,
    CIL_OPCODE_UNUSED_107 = 0x131,
    CIL_OPCODE_UNUSED_108 = 0x132,
    CIL_OPCODE_UNUSED_109 = 0x133,
    CIL_OPCODE_UNUSED_110 = 0x134,
    CIL_OPCODE_UNUSED_111 = 0x135,
    CIL_OPCODE_UNUSED_112 = 0x136,
    CIL_OPCODE_UNUSED_113 = 0x137,
    CIL_OPCODE_UNUSED_114 = 0x138,
    CIL_OPCODE_UNUSED_115 = 0x139,
    CIL_OPCODE_UNUSED_116 = 0x13A,
    CIL_OPCODE_UNUSED_117 = 0x13B,
    CIL_OPCODE_UNUSED_118 = 0x13C,
    CIL_OPCODE_UNUSED_119 = 0x13D,
    CIL_OPCODE_UNUSED_120 = 0x13E,
    CIL_OPCODE_UNUSED_121 = 0x13F,
    CIL_OPCODE_UNUSED_122 = 0x140,
    CIL_OPCODE_UNUSED_123 = 0x141,
    CIL_OPCODE_UNUSED_124 = 0x142,
    CIL_OPCODE_UNUSED_125 = 0x143,
    CIL_OPCODE_UNUSED_126 = 0x144,
    CIL_OPCODE_UNUSED_127 = 0x145,
    CIL_OPCODE_UNUSED_128 = 0x146,
    CIL_OPCODE_UNUSED_129 = 0x147,
    CIL_OPCODE_UNUSED_130 = 0x148,
    CIL_OPCODE_UNUSED_131 = 0x149,
    CIL_OPCODE_UNUSED_132 = 0x14A,
    CIL_OPCODE_UNUSED_133 = 0x14B,
    CIL_OPCODE_UNUSED_134 = 0x14C,
    CIL_OPCODE_UNUSED_135 = 0x14D,
    CIL_OPCODE_UNUSED_136 = 0x14E,
    CIL_OPCODE_UNUSED_137 = 0x14F,
    CIL_OPCODE_UNUSED_138 = 0x150,
    CIL_OPCODE_UNUSED_139 = 0x151,
    CIL_OPCODE_UNUSED_140 = 0x152,
    CIL_OPCODE_UNUSED_141 = 0x153,
    CIL_OPCODE_UNUSED_142 = 0x154,
    CIL_OPCODE_UNUSED_143 = 0x155,
    CIL_OPCODE_PREFIX7 = 0x156,
    CIL_OPCODE_PREFIX6 = 0x157,
    CIL_OPCODE_PREFIX5 = 0x158,
    CIL_OPCODE_PREFIX4 = 0x159,
    CIL_OPCODE_PREFIX3 = 0x15A,
    CIL_OPCODE_PREFIX2 = 0x15B,
    CIL_OPCODE_PREFIX1 = 0x15C,
    CIL_OPCODE_PREFIXREF = 0x15D,
    
    // Arithmetic overflow operations (2-byte opcodes)
    CIL_OPCODE_ADD_OVF = 0xD6,
    CIL_OPCODE_ADD_OVF_UN = 0xD7,
    CIL_OPCODE_MUL_OVF = 0xD8,
    CIL_OPCODE_MUL_OVF_UN = 0xD9,
    CIL_OPCODE_SUB_OVF = 0xDA,
    CIL_OPCODE_SUB_OVF_UN = 0xDB,
    CIL_OPCODE_DIV_OVF = 0xDC,
    CIL_OPCODE_DIV_OVF_UN = 0xDD
} cil_opcode_t;

// Instruction operand types
typedef enum {
    CIL_OPERAND_NONE,           // No operand
    CIL_OPERAND_BYTE,           // 1-byte operand
    CIL_OPERAND_SHORT,          // 2-byte operand
    CIL_OPERAND_INT,            // 4-byte operand
    CIL_OPERAND_LONG,           // 8-byte operand
    CIL_OPERAND_FLOAT,          // 4-byte float
    CIL_OPERAND_DOUBLE,         // 8-byte double
    CIL_OPERAND_TOKEN,          // Metadata token (4 bytes)
    CIL_OPERAND_BRANCH,         // Branch target (4 bytes)
    CIL_OPERAND_BRANCH_SHORT,   // Short branch target (1 byte)
    CIL_OPERAND_SWITCH,         // Switch table
    CIL_OPERAND_STRING,         // String token
    CIL_OPERAND_TYPE,           // Type token
    CIL_OPERAND_METHOD,         // Method token
    CIL_OPERAND_FIELD           // Field token
} cil_operand_type_t;

// CIL instruction structure
typedef struct {
    cil_opcode_t opcode;
    cil_operand_type_t operand_type;
    union {
        uint8_t byte_val;
        int16_t short_val;
        int32_t int_val;
        int64_t long_val;
        float float_val;
        double double_val;
        uint32_t token;
        int32_t branch_offset;
        uint8_t branch_offset_short;
        struct {
            uint32_t num_targets;
            int32_t* targets;
        } switch_table;
    } operand;
    size_t size;  // Total size of instruction in bytes
} cil_instruction_t;

// Decoder state
typedef struct {
    const uint8_t* bytecode;
    size_t bytecode_size;
    size_t offset;
    bool has_error;
    const char* error_message;
} cil_decoder_t;

// Function prototypes
cil_decoder_t* create_cil_decoder(const uint8_t* bytecode, size_t size);
void destroy_cil_decoder(cil_decoder_t* decoder);
cil_instruction_t* decode_next_instruction(cil_decoder_t* decoder);
bool has_more_instructions(cil_decoder_t* decoder);
const char* get_opcode_name(cil_opcode_t opcode);
cil_operand_type_t get_opcode_operand_type(cil_opcode_t opcode);
bool is_extended_opcode(uint8_t opcode);

#endif // IL_DECODER_H