#!/bin/bash
# GDB debugging script for CR3 switch failure

cd /home/scott/Repo/lux9-kernel

echo "=== CR3 Switch Debugging Setup ==="
echo "1. Starting QEMU with GDB server..."
echo "   Run this command in another terminal:"
echo "   qemu-system-x86_64 -M q35 -m 2G -cdrom lux9.iso -boot d -s -S -serial file:qemu.log &"
echo ""
echo "2. In GDB, connect to QEMU and debug:"
echo "   (gdb) target remote localhost:1234"
echo "   (gdb) symbol-file lux9.elf"
echo "   (gdb) source gdb_debug_cr3_switch.gdb"
echo ""
echo "=== Key Debug Points ==="
echo "- Break at setuppagetables() and trace the CR3 switch sequence"
echo "- Check if trampoline is copied correctly to 0x1000"
echo "- Verify CR3 switch: old CR3 -> new CR3"
echo "- Check if RIP after CR3 switch is in valid range"
echo "- Verify page table mappings after switch"
echo ""
echo "=== Common Issues to Check ==="
echo "1. Trampoline code corruption"
echo "   (gdb) x/20i 0x1000"
echo ""
echo "2. Page table validity"
echo "   (gdb) print *(u64int*)0x[cr3_value]"
echo ""
echo "3. Memory access after CR3 switch"
echo "   (gdb) x/10i $rip"
echo ""
echo "4. Stack corruption"
echo "   (gdb) x/20x $rsp"
echo ""
echo "If kernel hangs at CR3 switch, check:"
echo "- Is the trampoline code valid?"
echo "- Are page tables properly set up?"
echo "- Is the continuation address valid?"
echo "- Is there memory corruption in the page tables?"