# Limine configuration for 9front kernel on Lux

timeout: 0
verbose: yes
serial: yes

/9front on Lux (lux9)
    protocol: limine
    kernel_path: boot():/boot/lux9.elf
    cmdline: console=0 root=hd0:0 init_tests=1 secure.ramdisk.size=64M secure.ramdisk.encrypt=1 secure.ramdisk.audit=1 pebble.secure.budget=32M
    module_path: boot():/boot/initrd.tar
