#!/bin/bash
# Quick debug setup for CR3 switch failure

cd /home/scott/Repo/lux9-kernel

echo "=== QUICK CR3 SWITCH DEBUG ==="
echo ""
echo "Step 1: Start QEMU in GDB server mode (pause at startup):"
echo "qemu-system-x86_64 -M q35 -m 2G -cdrom lux9.iso -boot d -s -S -serial file:qemu.log -display none &"
echo ""
echo "Step 2: In another terminal, run GDB:"
echo "gdb lux9.elf"
echo ""
echo "Step 3: Connect to QEMU and load debug commands:"
echo "(gdb) target remote localhost:1234"
echo "(gdb) source gdb_debug_cr3_detailed.gdb"
echo "(gdb) continue"
echo ""
echo "=== IMMEDIATE THINGS TO CHECK ==="
echo ""
echo "A. Check trampoline execution sequence:"
echo "(gdb) break *cr3_switch_trampoline"
echo "(gdb) continue"
echo "# When you hit the breakpoint:"
echo "(gdb) info registers"          # Check parameters (RDI=new CR3, RSI=continuation)"
echo "(gdb) stepi"                   # Execute: mov %rsi,%rax"
echo "(gdb) stepi"                   # Execute: cli"
echo "(gdb) stepi"                   # Execute: mov %rdi,%cr3 <- THE CRITICAL ONE"
echo "(gdb) info registers"          # Check CR3 after switch"
echo "(gdb) stepi"                   # Execute: jmp *%rax"
echo ""
echo "B. If CR3 switch hangs, check:"
echo "(gdb) info registers"          # Is CR3 valid?"
echo "(gdb) x/10i $rip"              # What instruction are we stuck on?"
echo "(gdb) x/10i 0x1000"            # Is trampoline still intact?"
echo "(gdb) print continuation"      # Is continuation address valid?"
echo ""
echo "C. Check page table validity:"
echo "(gdb) print *(u64int*)$rdi"    # First entry of new page table"
echo "(gdb) print *(u64int*)($rdi+8)" # Second entry"
echo ""
echo "D. Most common failure modes:"
echo "1. Invalid continuation address (not in KZERO range)"
echo "2. Page table corruption"
echo "3. Trampoline corruption"
echo "4. Memory access after CR3 switch fails"