[main]
default_editor = "xdg-open %f"
magic = 14
memlimit = 1000
running_provers_max = 2
timelimit = 5.000000

[partial_prover]
name = "Alt-Ergo"
path = "/home/scott/.opam/coq-8.19/bin/alt-ergo"
version = "2.2.0"

[partial_prover]
name = "CVC4"
path = "/usr/bin/cvc4"
version = "1.8"

[partial_prover]
name = "Coq"
path = "/home/scott/.opam/coq-8.19/bin/coqtop"
version = "8.20.1"

[partial_prover]
name = "Yices"
path = "/usr/bin/yices"
version = "Yices"

[partial_prover]
name = "Yices"
path = "/usr/bin/yices-smt2"
version = "2.6.5"

[partial_prover]
name = "Z3"
path = "/usr/bin/z3"
version = "4.15.4"
