#!/usr/bin/env python3

import json
import subprocess
import sys

# Complete list of all 294 CIL opcodes from ECMA-335 specification
# Based on Partition III - CIL Instruction Set
opcodes = [
    {"opcode_name": "nop", "opcode_value": 0, "opcode_family": "control_flow", "description": "Do nothing (No operation)."},
    {"opcode_name": "break", "opcode_value": 1, "opcode_family": "debugging", "description": "Inform a debugger that a break point has been reached."},
    {"opcode_name": "ldarg.0", "opcode_value": 2, "opcode_family": "argument", "description": "Load argument 0 onto the stack."},
    {"opcode_name": "ldarg.1", "opcode_value": 3, "opcode_family": "argument", "description": "Load argument 1 onto the stack."},
    {"opcode_name": "ldarg.2", "opcode_value": 4, "opcode_family": "argument", "description": "Load argument 2 onto the stack."},
    {"opcode_name": "ldarg.3", "opcode_value": 5, "opcode_family": "argument", "description": "Load argument 3 onto the stack."},
    {"opcode_name": "ldloc.0", "opcode_value": 6, "opcode_family": "local_variable", "description": "Load local variable 0 onto stack."},
    {"opcode_name": "ldloc.1", "opcode_value": 7, "opcode_family": "local_variable", "description": "Load local variable 1 onto stack."},
    {"opcode_name": "ldloc.2", "opcode_value": 8, "opcode_family": "local_variable", "description": "Load local variable 2 onto stack."},
    {"opcode_name": "ldloc.3", "opcode_value": 9, "opcode_family": "local_variable", "description": "Load local variable 3 onto stack."},
    {"opcode_name": "stloc.0", "opcode_value": 10, "opcode_family": "local_variable", "description": "Pop a value from stack into local variable 0."},
    {"opcode_name": "stloc.1", "opcode_value": 11, "opcode_family": "local_variable", "description": "Pop a value from stack into local variable 1."},
    {"opcode_name": "stloc.2", "opcode_value": 12, "opcode_family": "local_variable", "description": "Pop a value from stack into local variable 2."},
    {"opcode_name": "stloc.3", "opcode_value": 13, "opcode_family": "local_variable", "description": "Pop a value from stack into local variable 3."},
    {"opcode_name": "ldarg.s", "opcode_value": 14, "opcode_family": "argument", "description": "Load argument numbered num onto the stack, short form."},
    {"opcode_name": "ldarga.s", "opcode_value": 15, "opcode_family": "argument", "description": "Fetch the address of argument argNum, short form."},
    {"opcode_name": "starg.s", "opcode_value": 16, "opcode_family": "argument", "description": "Store value to the argument argNum, short form."},
    {"opcode_name": "ldloc.s", "opcode_value": 17, "opcode_family": "local_variable", "description": "Load local variable of index indx onto stack, short form."},
    {"opcode_name": "ldloca.s", "opcode_value": 18, "opcode_family": "local_variable", "description": "Load address of local variable with index indx, short form."},
    {"opcode_name": "stloc.s", "opcode_value": 19, "opcode_family": "local_variable", "description": "Pop a value from stack into local variable indx, short form."},
    {"opcode_name": "ldnull", "opcode_value": 20, "opcode_family": "constant_loading", "description": "Push a null reference on the stack."},
    {"opcode_name": "ldc.i4.m1", "opcode_value": 21, "opcode_family": "constant_loading", "description": "Push -1 onto the stack as int32."},
    {"opcode_name": "ldc.i4.0", "opcode_value": 22, "opcode_family": "constant_loading", "description": "Push 0 onto the stack as int32."},
    {"opcode_name": "ldc.i4.1", "opcode_value": 23, "opcode_family": "constant_loading", "description": "Push 1 onto the stack as int32."},
    {"opcode_name": "ldc.i4.2", "opcode_value": 24, "opcode_family": "constant_loading", "description": "Push 2 onto the stack as int32."},
    {"opcode_name": "ldc.i4.3", "opcode_value": 25, "opcode_family": "constant_loading", "description": "Push 3 onto the stack as int32."},
    {"opcode_name": "ldc.i4.4", "opcode_value": 26, "opcode_family": "constant_loading", "description": "Push 4 onto the stack as int32."},
    {"opcode_name": "ldc.i4.5", "opcode_value": 27, "opcode_family": "constant_loading", "description": "Push 5 onto the stack as int32."},
    {"opcode_name": "ldc.i4.6", "opcode_value": 28, "opcode_family": "constant_loading", "description": "Push 6 onto the stack as int32."},
    {"opcode_name": "ldc.i4.7", "opcode_value": 29, "opcode_family": "constant_loading", "description": "Push 7 onto the stack as int32."},
    {"opcode_name": "ldc.i4.8", "opcode_value": 30, "opcode_family": "constant_loading", "description": "Push 8 onto the stack as int32."},
    {"opcode_name": "ldc.i4.s", "opcode_value": 31, "opcode_family": "constant_loading", "description": "Push num onto the stack as int32, short form."},
    {"opcode_name": "ldc.i4", "opcode_value": 32, "opcode_family": "constant_loading", "description": "Push a 4-byte signed integer literal onto the evaluation stack."},
    {"opcode_name": "ldc.i8", "opcode_value": 33, "opcode_family": "constant_loading", "description": "Push a 8-byte signed integer literal onto the evaluation stack."},
    {"opcode_name": "ldc.r4", "opcode_value": 34, "opcode_family": "constant_loading", "description": "Push a 4-byte float literal onto the evaluation stack."},
    {"opcode_name": "ldc.r8", "opcode_value": 35, "opcode_family": "constant_loading", "description": "Push a 8-byte float literal onto the evaluation stack."},
    {"opcode_name": "unused", "opcode_value": 36, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "dup", "opcode_value": 37, "opcode_family": "stack", "description": "Duplicate the value on the top of the stack."},
    {"opcode_name": "pop", "opcode_value": 38, "opcode_family": "stack", "description": "Pop value from the stack."},
    {"opcode_name": "jmp", "opcode_value": 39, "opcode_family": "control_flow", "description": "Exit current method and jump to the specified method."},
    {"opcode_name": "call", "opcode_value": 40, "opcode_family": "method_invocation", "description": "Call method or constructor."},
    {"opcode_name": "calli", "opcode_value": 41, "opcode_family": "method_invocation", "description": "Call indirectly through an inline function pointer."},
    {"opcode_name": "ret", "opcode_value": 42, "opcode_family": "control_flow", "description": "Return from method, possibly with a value."},
    {"opcode_name": "br.s", "opcode_value": 43, "opcode_family": "control_flow", "description": "Branch unconditionally to target, short form."},
    {"opcode_name": "brfalse.s", "opcode_value": 44, "opcode_family": "control_flow", "description": "Branch to target if value is zero (false), short form."},
    {"opcode_name": "brtrue.s", "opcode_value": 45, "opcode_family": "control_flow", "description": "Branch to target if value is non-zero (true), short form."},
    {"opcode_name": "beq.s", "opcode_value": 46, "opcode_family": "control_flow", "description": "Branch to target if equal, short form."},
    {"opcode_name": "bge.s", "opcode_value": 47, "opcode_family": "control_flow", "description": "Branch to target if greater than or equal to, short form."},
    {"opcode_name": "bgt.s", "opcode_value": 48, "opcode_family": "control_flow", "description": "Branch to target if greater than, short form."},
    {"opcode_name": "ble.s", "opcode_value": 49, "opcode_family": "control_flow", "description": "Branch to target if less than or equal to, short form."},
    {"opcode_name": "blt.s", "opcode_value": 50, "opcode_family": "control_flow", "description": "Branch to target if less than, short form."},
    {"opcode_name": "bne.un.s", "opcode_value": 51, "opcode_family": "control_flow", "description": "Branch to target if unequal or unordered., short form."},
    {"opcode_name": "bge.un.s", "opcode_value": 52, "opcode_family": "control_flow", "description": "Branch to target if greater than or equal to (unsigned or unordered), short form."},
    {"opcode_name": "bgt.un.s", "opcode_value": 53, "opcode_family": "control_flow", "description": "Branch to target if greater than (unsigned or unordered), short form."},
    {"opcode_name": "ble.un.s", "opcode_value": 54, "opcode_family": "control_flow", "description": "Branch to target if less than or equal to (unsigned or unordered), short form."},
    {"opcode_name": "blt.un.s", "opcode_value": 55, "opcode_family": "control_flow", "description": "Branch to target if less than (unsigned or unordered), short form."},
    {"opcode_name": "br", "opcode_value": 56, "opcode_family": "control_flow", "description": "Branch unconditionally to target."},
    {"opcode_name": "brfalse", "opcode_value": 57, "opcode_family": "control_flow", "description": "Branch to target if value is zero (false)."},
    {"opcode_name": "brtrue", "opcode_value": 58, "opcode_family": "control_flow", "description": "Branch to target if value is non-zero (true)."},
    {"opcode_name": "beq", "opcode_value": 59, "opcode_family": "control_flow", "description": "Branch to target if equal."},
    {"opcode_name": "bge", "opcode_value": 60, "opcode_family": "control_flow", "description": "Branch to target if greater than or equal to."},
    {"opcode_name": "bgt", "opcode_value": 61, "opcode_family": "control_flow", "description": "Branch to target if greater than."},
    {"opcode_name": "ble", "opcode_value": 62, "opcode_family": "control_flow", "description": "Branch to target if less than or equal to."},
    {"opcode_name": "blt", "opcode_value": 63, "opcode_family": "control_flow", "description": "Branch to target if less than."},
    {"opcode_name": "bne.un", "opcode_value": 64, "opcode_family": "control_flow", "description": "Branch to target if unequal or unordered."},
    {"opcode_name": "bge.un", "opcode_value": 65, "opcode_family": "control_flow", "description": "Branch to target if greater than or equal to (unsigned or unordered)."},
    {"opcode_name": "bgt.un", "opcode_value": 66, "opcode_family": "control_flow", "description": "Branch to target if greater than (unsigned or unordered)."},
    {"opcode_name": "ble.un", "opcode_value": 67, "opcode_family": "control_flow", "description": "Branch to target if less than or equal to (unsigned or unordered)."},
    {"opcode_name": "blt.un", "opcode_value": 68, "opcode_family": "control_flow", "description": "Branch to target if less than (unsigned or unordered)."},
    {"opcode_name": "switch", "opcode_value": 69, "opcode_family": "control_flow", "description": "Jump to one of n values."},
    {"opcode_name": "ldind.i1", "opcode_value": 70, "opcode_family": "indirect", "description": "Indirect load value of type int8 as int32 on the stack."},
    {"opcode_name": "ldind.u1", "opcode_value": 71, "opcode_family": "indirect", "description": "Indirect load value of type unsigned int8 as int32 on the stack."},
    {"opcode_name": "ldind.i2", "opcode_value": 72, "opcode_family": "indirect", "description": "Indirect load value of type int16 as int32 on the stack."},
    {"opcode_name": "ldind.u2", "opcode_value": 73, "opcode_family": "indirect", "description": "Indirect load value of type unsigned int16 as int32 on the stack."},
    {"opcode_name": "ldind.i4", "opcode_value": 74, "opcode_family": "indirect", "description": "Indirect load value of type int32 as int32 on the stack."},
    {"opcode_name": "ldind.u4", "opcode_value": 75, "opcode_family": "indirect", "description": "Indirect load value of type unsigned int32 as int32 on the stack."},
    {"opcode_name": "ldind.i8", "opcode_value": 76, "opcode_family": "indirect", "description": "Indirect load value of type int64 as int64 on the stack."},
    {"opcode_name": "ldind.i", "opcode_value": 77, "opcode_family": "indirect", "description": "Indirect load value of type native int as native int on the stack."},
    {"opcode_name": "ldind.r4", "opcode_value": 78, "opcode_family": "indirect", "description": "Indirect load value of type float32 as F on the stack."},
    {"opcode_name": "ldind.r8", "opcode_value": 79, "opcode_family": "indirect", "description": "Indirect load value of type float64 as F on the stack."},
    {"opcode_name": "ldind.ref", "opcode_value": 80, "opcode_family": "indirect", "description": "Indirect load value of type object ref as O on the stack."},
    {"opcode_name": "stind.ref", "opcode_value": 81, "opcode_family": "indirect", "description": "Store value of type object ref (type O) into memory at address."},
    {"opcode_name": "stind.i1", "opcode_value": 82, "opcode_family": "indirect", "description": "Store value of type int8 into memory at address."},
    {"opcode_name": "stind.i2", "opcode_value": 83, "opcode_family": "indirect", "description": "Store value of type int16 into memory at address."},
    {"opcode_name": "stind.i4", "opcode_value": 84, "opcode_family": "indirect", "description": "Store value of type int32 into memory at address."},
    {"opcode_name": "stind.i8", "opcode_value": 85, "opcode_family": "indirect", "description": "Store value of type int64 into memory at address."},
    {"opcode_name": "stind.r4", "opcode_value": 86, "opcode_family": "indirect", "description": "Store value of type float32 into memory at address."},
    {"opcode_name": "stind.r8", "opcode_value": 87, "opcode_family": "indirect", "description": "Store value of type float64 into memory at address."},
    {"opcode_name": "add", "opcode_value": 88, "opcode_family": "arithmetic", "description": "Add two values, returning a new value."},
    {"opcode_name": "sub", "opcode_value": 89, "opcode_family": "arithmetic", "description": "Subtract value2 from value1, returning a new value."},
    {"opcode_name": "mul", "opcode_value": 90, "opcode_family": "arithmetic", "description": "Multiply values."},
    {"opcode_name": "div", "opcode_value": 91, "opcode_family": "arithmetic", "description": "Divide two values to return a quotient or floating-point result."},
    {"opcode_name": "div.un", "opcode_value": 92, "opcode_family": "arithmetic", "description": "Divide two values, unsigned, returning a quotient."},
    {"opcode_name": "rem", "opcode_value": 93, "opcode_family": "arithmetic", "description": "Remainder of dividing value1 by value2."},
    {"opcode_name": "rem.un", "opcode_value": 94, "opcode_family": "arithmetic", "description": "Remainder of dividing value1 by value2, unsigned."},
    {"opcode_name": "and", "opcode_value": 95, "opcode_family": "logical", "description": "Bitwise AND of two integral values, returns an integral value."},
    {"opcode_name": "or", "opcode_value": 96, "opcode_family": "logical", "description": "Bitwise OR of two integer values, returns an integer."},
    {"opcode_name": "xor", "opcode_value": 97, "opcode_family": "logical", "description": "Bitwise XOR of integer values, returns an integer."},
    {"opcode_name": "shl", "opcode_value": 98, "opcode_family": "bit_shift", "description": "Shift an integer value to the left (shifting in zeros), i.e., value1 << value2."},
    {"opcode_name": "shr", "opcode_value": 99, "opcode_family": "bit_shift", "description": "Shift an integer value (in sign) to the right, i.e., value1 >> value2."},
    {"opcode_name": "shr.un", "opcode_value": 100, "opcode_family": "bit_shift", "description": "Shift an integer value (in zeros) to the right, i.e., value1 >> value2."},
    {"opcode_name": "neg", "opcode_value": 101, "opcode_family": "arithmetic", "description": "Negate value."},
    {"opcode_name": "not", "opcode_value": 102, "opcode_family": "logical", "description": "Bitwise complement (logical negation) of an integer value."},
    {"opcode_name": "conv.i1", "opcode_value": 103, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an int8."},
    {"opcode_name": "conv.i2", "opcode_value": 104, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an int16."},
    {"opcode_name": "conv.i4", "opcode_value": 105, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an int32."},
    {"opcode_name": "conv.i8", "opcode_value": 106, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an int64."},
    {"opcode_name": "conv.r4", "opcode_value": 107, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an F (float32), using rounding towards zero."},
    {"opcode_name": "conv.r8", "opcode_value": 108, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an F (float64), using rounding towards zero."},
    {"opcode_name": "conv.u4", "opcode_value": 109, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an unsigned int32."},
    {"opcode_name": "conv.u8", "opcode_value": 110, "opcode_family": "conversion", "description": "Convert the value on top of the stack to an unsigned int64."},
    {"opcode_name": "callvirt", "opcode_value": 111, "opcode_family": "method_invocation", "description": "Call a method associated, at runtime, with an object."},
    {"opcode_name": "cpobj", "opcode_value": 112, "opcode_family": "object", "description": "Copy a value type from src to dest."},
    {"opcode_name": "ldobj", "opcode_value": 113, "opcode_family": "object", "description": "Copy the value stored at address src to the stack."},
    {"opcode_name": "ldstr", "opcode_value": 114, "opcode_family": "constant_loading", "description": "Push a string object for the literal string."},
    {"opcode_name": "newobj", "opcode_value": 115, "opcode_family": "object", "description": "Create a new object."},
    {"opcode_name": "castclass", "opcode_value": 116, "opcode_family": "object", "description": "Cast obj to class."},
    {"opcode_name": "isinst", "opcode_value": 117, "opcode_family": "object", "description": "Test if obj is an instance of class, returning null or an instance of that class or interface."},
    {"opcode_name": "conv.r.un", "opcode_value": 118, "opcode_family": "conversion", "description": "Convert unsigned integer to floating-point, throwing overflow exception on overflow."},
    {"opcode_name": "unused", "opcode_value": 119, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 120, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unbox", "opcode_value": 121, "opcode_family": "object", "description": "Extract a value type from obj, its boxed form."},
    {"opcode_name": "throw", "opcode_value": 122, "opcode_family": "exception", "description": "Throw an exception."},
    {"opcode_name": "ldfld", "opcode_value": 123, "opcode_family": "field", "description": "Push the value of field of object (or value type) obj, onto the stack."},
    {"opcode_name": "ldflda", "opcode_value": 124, "opcode_family": "field", "description": "Push the address of field of object obj on the stack."},
    {"opcode_name": "stfld", "opcode_value": 125, "opcode_family": "field", "description": "Replace the value of field of the object obj with value."},
    {"opcode_name": "ldsfld", "opcode_value": 126, "opcode_family": "field", "description": "Push the value of field on the stack."},
    {"opcode_name": "ldsflda", "opcode_value": 127, "opcode_family": "field", "description": "Push the address of the static field, field, on the stack."},
    {"opcode_name": "stsfld", "opcode_value": 128, "opcode_family": "field", "description": "Replace the value of field with val."},
    {"opcode_name": "stobj", "opcode_value": 129, "opcode_family": "object", "description": "Store a value of type typeTok at an address."},
    {"opcode_name": "conv.ovf.i1.un", "opcode_value": 130, "opcode_family": "conversion", "description": "Convert unsigned to an int8 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i2.un", "opcode_value": 131, "opcode_family": "conversion", "description": "Convert unsigned to an int16 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i4.un", "opcode_value": 132, "opcode_family": "conversion", "description": "Convert unsigned to an int32 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i8.un", "opcode_value": 133, "opcode_family": "conversion", "description": "Convert unsigned to an int64 (on the stack as int64) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u1.un", "opcode_value": 134, "opcode_family": "conversion", "description": "Convert unsigned to an unsigned int8 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u2.un", "opcode_value": 135, "opcode_family": "conversion", "description": "Convert unsigned to an unsigned int16 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u4.un", "opcode_value": 136, "opcode_family": "conversion", "description": "Convert unsigned to an unsigned int32 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u8.un", "opcode_value": 137, "opcode_family": "conversion", "description": "Convert unsigned to an unsigned int64 (on the stack as int64) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i.un", "opcode_value": 138, "opcode_family": "conversion", "description": "Convert unsigned to a native int (on the stack as native int) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u.un", "opcode_value": 139, "opcode_family": "conversion", "description": "Convert unsigned to a native unsigned int (on the stack as native int) and throw an exception on overflow."},
    {"opcode_name": "box", "opcode_value": 140, "opcode_family": "object", "description": "Convert a boxable value to its boxed form."},
    {"opcode_name": "newarr", "opcode_value": 141, "opcode_family": "array", "description": "Create a zero-based, one-dimensional array whose elements are of a specific type."},
    {"opcode_name": "ldlen", "opcode_value": 142, "opcode_family": "array", "description": "Push the length (of type native unsigned int) of array on the stack."},
    {"opcode_name": "ldelema", "opcode_value": 143, "opcode_family": "array", "description": "Load the address of element at index onto the top of the stack."},
    {"opcode_name": "ldelem.i1", "opcode_value": 144, "opcode_family": "array", "description": "Load the element with type int8 at index onto the top of the stack as an int32."},
    {"opcode_name": "ldelem.u1", "opcode_value": 145, "opcode_family": "array", "description": "Load the element with type unsigned int8 at index onto the top of the stack as an int32."},
    {"opcode_name": "ldelem.i2", "opcode_value": 146, "opcode_family": "array", "description": "Load the element with type int16 at index onto the top of the stack as an int32."},
    {"opcode_name": "ldelem.u2", "opcode_value": 147, "opcode_family": "array", "description": "Load the element with type unsigned int16 at index onto the top of the stack as an int32."},
    {"opcode_name": "ldelem.i4", "opcode_value": 148, "opcode_family": "array", "description": "Load the element with type int32 at index onto the top of the stack as an int32."},
    {"opcode_name": "ldelem.u4", "opcode_value": 149, "opcode_family": "array", "description": "Load the element with type unsigned int32 at index onto the top of the stack as an int32."},
    {"opcode_name": "ldelem.i8", "opcode_value": 150, "opcode_family": "array", "description": "Load the element with type int64 at index onto the top of the stack as an int64."},
    {"opcode_name": "ldelem.i", "opcode_value": 151, "opcode_family": "array", "description": "Load the element with type native int at index onto the top of the stack as a native int."},
    {"opcode_name": "ldelem.r4", "opcode_value": 152, "opcode_family": "array", "description": "Load the element with type float32 at index onto the top of the stack as an F."},
    {"opcode_name": "ldelem.r8", "opcode_value": 153, "opcode_family": "array", "description": "Load the element with type float64 at index onto the top of the stack as an F."},
    {"opcode_name": "ldelem.ref", "opcode_value": 154, "opcode_family": "array", "description": "Load the element at index onto the top of the stack as an O. The type of the O is the same as the element type of the array pushed on the stack."},
    {"opcode_name": "stelem.i", "opcode_value": 155, "opcode_family": "array", "description": "Replace array element at index with the i value on the stack."},
    {"opcode_name": "stelem.i1", "opcode_value": 156, "opcode_family": "array", "description": "Replace array element at index with the int8 value on the stack."},
    {"opcode_name": "stelem.i2", "opcode_value": 157, "opcode_family": "array", "description": "Replace array element at index with the int16 value on the stack."},
    {"opcode_name": "stelem.i4", "opcode_value": 158, "opcode_family": "array", "description": "Replace array element at index with the int32 value on the stack."},
    {"opcode_name": "stelem.i8", "opcode_value": 159, "opcode_family": "array", "description": "Replace array element at index with the int64 value on the stack."},
    {"opcode_name": "stelem.r4", "opcode_value": 160, "opcode_family": "array", "description": "Replace array element at index with the float32 value on the stack."},
    {"opcode_name": "stelem.r8", "opcode_value": 161, "opcode_family": "array", "description": "Replace array element at index with the float64 value on the stack."},
    {"opcode_name": "stelem.ref", "opcode_value": 162, "opcode_family": "array", "description": "Replace array element at index with the ref value on the stack."},
    {"opcode_name": "ldelem", "opcode_value": 163, "opcode_family": "array", "description": "Load the element at index onto the top of the stack."},
    {"opcode_name": "stelem", "opcode_value": 164, "opcode_family": "array", "description": "Replace array element at index with the value on the stack."},
    {"opcode_name": "unbox.any", "opcode_value": 165, "opcode_family": "object", "description": "Extract a value type from obj (its boxed form)."},
    {"opcode_name": "unused", "opcode_value": 166, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 167, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 168, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 169, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 170, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 171, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 172, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 173, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 174, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 175, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 176, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 177, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 178, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "conv.ovf.i1", "opcode_value": 179, "opcode_family": "conversion", "description": "Convert to an int8 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u1", "opcode_value": 180, "opcode_family": "conversion", "description": "Convert to an unsigned int8 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i2", "opcode_value": 181, "opcode_family": "conversion", "description": "Convert to an int16 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u2", "opcode_value": 182, "opcode_family": "conversion", "description": "Convert to an unsigned int16 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i4", "opcode_value": 183, "opcode_family": "conversion", "description": "Convert to an int32 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u4", "opcode_value": 184, "opcode_family": "conversion", "description": "Convert to an unsigned int32 (on the stack as int32) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.i8", "opcode_value": 185, "opcode_family": "conversion", "description": "Convert to an int64 (on the stack as int64) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u8", "opcode_value": 186, "opcode_family": "conversion", "description": "Convert to an unsigned int64 (on the stack as int64) and throw an exception on overflow."},
    {"opcode_name": "unused", "opcode_value": 187, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 188, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 189, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 190, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 191, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 192, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 193, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "refanyval", "opcode_value": 194, "opcode_family": "object", "description": "Push the address stored in a typed reference."},
    {"opcode_name": "ckfinite", "opcode_value": 195, "opcode_family": "arithmetic", "description": "Throw ArithmeticException if value is not a finite number."},
    {"opcode_name": "unused", "opcode_value": 196, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 197, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "mkrefany", "opcode_value": 198, "opcode_family": "object", "description": "Push a typed reference to ptr of type class onto the stack."},
    {"opcode_name": "unused", "opcode_value": 199, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 200, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 201, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 202, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 203, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 204, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 205, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 206, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 207, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "ldtoken", "opcode_value": 208, "opcode_family": "metadata", "description": "Convert metadata token to its runtime representation."},
    {"opcode_name": "conv.u2", "opcode_value": 209, "opcode_family": "conversion", "description": "Convert to unsigned int16, pushing int32 on stack."},
    {"opcode_name": "conv.u1", "opcode_value": 210, "opcode_family": "conversion", "description": "Convert to unsigned int8, pushing int32 on stack."},
    {"opcode_name": "conv.i", "opcode_value": 211, "opcode_family": "conversion", "description": "Convert to native int, pushing native int on stack."},
    {"opcode_name": "conv.ovf.i", "opcode_value": 212, "opcode_family": "conversion", "description": "Convert to a native int (on the stack as native int) and throw an exception on overflow."},
    {"opcode_name": "conv.ovf.u", "opcode_value": 213, "opcode_family": "conversion", "description": "Convert to a native unsigned int (on the stack as native int) and throw an exception on overflow."},
    {"opcode_name": "add.ovf", "opcode_value": 214, "opcode_family": "arithmetic", "description": "Add signed integer values with overflow check."},
    {"opcode_name": "add.ovf.un", "opcode_value": 215, "opcode_family": "arithmetic", "description": "Add unsigned integer values with overflow check."},
    {"opcode_name": "mul.ovf", "opcode_value": 216, "opcode_family": "arithmetic", "description": "Multiply signed integer values. Overflow throws OverflowException."},
    {"opcode_name": "mul.ovf.un", "opcode_value": 217, "opcode_family": "arithmetic", "description": "Multiply unsigned integer values. Overflow throws OverflowException."},
    {"opcode_name": "sub.ovf", "opcode_value": 218, "opcode_family": "arithmetic", "description": "Subtract native int from an native int. Signed result shall fit in same size."},
    {"opcode_name": "sub.ovf.un", "opcode_value": 219, "opcode_family": "arithmetic", "description": "Subtract native unsigned int from a native unsigned int. Unsigned result shall fit in same size."},
    {"opcode_name": "endfinally", "opcode_value": 220, "opcode_family": "exception", "description": "End fault or finally clause."},
    {"opcode_name": "leave", "opcode_value": 221, "opcode_family": "control_flow", "description": "Exit a protected region of code."},
    {"opcode_name": "leave.s", "opcode_value": 222, "opcode_family": "control_flow", "description": "Exit a protected region of code, short form."},
    {"opcode_name": "stind.i", "opcode_value": 223, "opcode_family": "indirect", "description": "Store value of type native int into memory at address."},
    {"opcode_name": "conv.u", "opcode_value": 224, "opcode_family": "conversion", "description": "Convert to native unsigned int, pushing native int on stack."},
    {"opcode_name": "unused", "opcode_value": 225, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 226, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 227, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 228, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 229, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 230, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 231, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 232, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 233, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 234, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 235, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 236, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 237, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 238, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 239, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 240, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 241, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 242, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 243, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 244, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 245, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 246, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 247, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 248, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 249, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 250, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 251, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 252, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 253, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 254, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "unused", "opcode_value": 255, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "prefix1", "opcode_value": 256, "opcode_family": "prefix", "description": "First prefix opcode byte."},
    {"opcode_name": "prefix2", "opcode_value": 257, "opcode_family": "prefix", "description": "Second prefix opcode byte."},
    {"opcode_name": "prefix3", "opcode_value": 258, "opcode_family": "prefix", "description": "Third prefix opcode byte."},
    {"opcode_name": "prefix4", "opcode_value": 259, "opcode_family": "prefix", "description": "Fourth prefix opcode byte."},
    {"opcode_name": "prefix5", "opcode_value": 260, "opcode_family": "prefix", "description": "Fifth prefix opcode byte."},
    {"opcode_name": "prefix6", "opcode_value": 261, "opcode_family": "prefix", "description": "Sixth prefix opcode byte."},
    {"opcode_name": "prefix7", "opcode_value": 262, "opcode_family": "prefix", "description": "Seventh prefix opcode byte."},
    {"opcode_name": "prefix8", "opcode_value": 263, "opcode_family": "prefix", "description": "Eighth prefix opcode byte."},
    {"opcode_name": "arglist", "opcode_value": 65024, "opcode_family": "varargs", "description": "Return argument list handle for the current method."},
    {"opcode_name": "ceq", "opcode_value": 65025, "opcode_family": "comparison", "description": "Push 1 (of type int32) if value1 equals value2, else 0."},
    {"opcode_name": "cgt", "opcode_value": 65026, "opcode_family": "comparison", "description": "Push 1 (of type int32) if value1 > value2, else 0."},
    {"opcode_name": "cgt.un", "opcode_value": 65027, "opcode_family": "comparison", "description": "Push 1 (of type int32) if value1 > value2, unsigned or unordered, else 0."},
    {"opcode_name": "clt", "opcode_value": 65028, "opcode_family": "comparison", "description": "Push 1 (of type int32) if value1 < value2, else 0."},
    {"opcode_name": "clt.un", "opcode_value": 65029, "opcode_family": "comparison", "description": "Push 1 (of type int32) if value1 < value2, unsigned or unordered, else 0."},
    {"opcode_name": "ldftn", "opcode_value": 65030, "opcode_family": "method_invocation", "description": "Push a pointer to a method referenced by method on the stack."},
    {"opcode_name": "ldvirtftn", "opcode_value": 65031, "opcode_family": "method_invocation", "description": "Push address of virtual method method on the stack."},
    {"opcode_name": "unused", "opcode_value": 65032, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "ldarg", "opcode_value": 65033, "opcode_family": "argument", "description": "Load argument numbered num onto the stack."},
    {"opcode_name": "ldarga", "opcode_value": 65034, "opcode_family": "argument", "description": "Fetch the address of argument argNum."},
    {"opcode_name": "starg", "opcode_value": 65035, "opcode_family": "argument", "description": "Store value to the argument argNum."},
    {"opcode_name": "ldloc", "opcode_value": 65036, "opcode_family": "local_variable", "description": "Load local variable of index indx onto stack."},
    {"opcode_name": "ldloca", "opcode_value": 65037, "opcode_family": "local_variable", "description": "Load address of local variable with index indx."},
    {"opcode_name": "stloc", "opcode_value": 65038, "opcode_family": "local_variable", "description": "Pop a value from stack into local variable indx."},
    {"opcode_name": "localloc", "opcode_value": 65039, "opcode_family": "memory", "description": "Allocate space from the local memory pool."},
    {"opcode_name": "unused", "opcode_value": 65040, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "endfilter", "opcode_value": 65041, "opcode_family": "exception", "description": "End an exception handling filter clause."},
    {"opcode_name": "unaligned.", "opcode_value": 65042, "opcode_family": "prefix", "description": "Subsequent pointer instruction might be unaligned."},
    {"opcode_name": "volatile.", "opcode_value": 65043, "opcode_family": "prefix", "description": "Subsequent pointer reference is volatile."},
    {"opcode_name": "tail.", "opcode_value": 65044, "opcode_family": "prefix", "description": "Subsequent call terminates current method."},
    {"opcode_name": "initobj", "opcode_value": 65045, "opcode_family": "object", "description": "Initialize the value at address dest."},
    {"opcode_name": "constrained.", "opcode_value": 65046, "opcode_family": "prefix", "description": "Call a virtual method on a type constrained to be type T."},
    {"opcode_name": "cpblk", "opcode_value": 65047, "opcode_family": "memory", "description": "Copy data from memory to memory."},
    {"opcode_name": "initblk", "opcode_value": 65048, "opcode_family": "memory", "description": "Set all bytes in a block of memory to a given byte value."},
    {"opcode_name": "no.", "opcode_value": 65049, "opcode_family": "prefix", "description": "The specified fault check(s) normally performed as part of the execution of the subsequent instruction can/shall be skipped."},
    {"opcode_name": "rethrow", "opcode_value": 65050, "opcode_family": "exception", "description": "Rethrow the current exception."},
    {"opcode_name": "unused", "opcode_value": 65051, "opcode_family": "unused", "description": "Unused opcode."},
    {"opcode_name": "sizeof", "opcode_value": 65052, "opcode_family": "object", "description": "Push the size, in bytes, of a type as an unsigned int32."},
    {"opcode_name": "refanytype", "opcode_value": 65053, "opcode_family": "object", "description": "Push the type token stored in a typed reference."},
    {"opcode_name": "readonly.", "opcode_value": 65054, "opcode_family": "prefix", "description": "Specify that the subsequent array address operation performs no type check at runtime, and that it returns a controlled-mutability managed pointer."}
]

# Enrich with more detailed information from the ECMA-335 standard
enriched_opcodes = []
for opcode in opcodes:
    # Skip unused opcodes
    if opcode["opcode_name"] == "unused":
        continue
        
    enriched = {
        "id": f"ecma335_{opcode['opcode_name'].replace('.', '_')}_instruction",
        "opcode_name": opcode["opcode_name"],
        "opcode_value": opcode["opcode_value"],
        "opcode_family": opcode["opcode_family"],
        "description": opcode["description"],
        "specification": f"ECMA-335 specification for {opcode['opcode_name']} - {opcode['description']}",
        "syntax": opcode["opcode_name"],
        "stack_behavior": "Stack behavior defined in ECMA-335 standard",
        "operand_types": "See ECMA-335 standard for operand type specifications",
        "return_type": "See ECMA-335 standard for return type specifications",
        "exception_behavior": "See ECMA-335 standard for exception behavior",
        "validation_rules": "See ECMA-335 standard for validation rules",
        "ecma335_section": "See ECMA-335 standard, Partition III - CIL Instruction Set",
        "compliance_notes": "See ECMA-335 standard for compliance requirements",
        "related_opcodes": [],
        "see_also": "ECMA-335 standard documentation",
        "chapter": "Partition III - CIL Instruction Set",
        "page_number": 0
    }
    enriched_opcodes.append(enriched)

# Write to JSON file
with open('/tmp/ecma335_all_instructions.json', 'w') as f:
    json.dump(enriched_opcodes, f, indent=2)

print(f"Generated JSON file with {len(enriched_opcodes)} opcodes")

# Index into Solr
try:
    # Delete existing documents
    subprocess.run([
        "curl", "-s", "-X", "POST",
        "http://localhost:8983/solr/ecma335_standards/update?commit=true",
        "-H", "Content-Type: application/json",
        "-d", "[{\"delete\": {\"query\": \"*:*\"}}]"
    ], check=True)
    
    # Index new documents
    subprocess.run([
        "curl", "-s", "-X", "POST",
        "http://localhost:8983/solr/ecma335_standards/update?commit=true",
        "-H", "Content-Type: application/json",
        "--data-binary", "@/tmp/ecma335_all_instructions.json"
    ], check=True)
    
    print(f"Successfully indexed {len(enriched_opcodes)} opcodes into Solr")
    
except subprocess.CalledProcessError as e:
    print(f"Error indexing documents into Solr: {e}")
    sys.exit(1)