<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoStdLib>true</NoStdLib>
    <NoConfig>true</NoConfig>
    <AutoExplicitAssembly>false</AutoExplicitAssembly>
    <AssemblyExtensions>.dll</AssemblyExtensions>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <NoCompilerStandardLib>true</NoCompilerStandardLib>
    <AssemblyName>mscorlib</AssemblyName>
    <!-- Define constants for .NET Core BCL source -->
    <DefineConstants>NETCOREAPP;NET9_0;TARGET_UNIX;TARGET_LINUX;TARGET_64BIT;TARGET_AMD64;INTERNAL_NULLABLE_ATTRIBUTES;SYSTEM_PRIVATE_CORELIB</DefineConstants>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>

</Project>
