#ifndef WASI_CONSTANTS_H
#define WASI_CONSTANTS_H

/* WASI Event Types */
#define WASI_EVENTTYPE_CLOCK 0
#define WASI_EVENTTYPE_FD_READ 1
#define WASI_EVENTTYPE_FD_WRITE 2

/* WASI Subscription Flags */
#define WASI_SUBSCRIPTION_CLOCK_ABSTIME 1

/* WASI Sizes */
#define WASI_SUBSCRIPTION_SIZE 48
#define WASI_EVENT_SIZE 32
#define WASI_FILESTAT_SIZE 64

/* WASI Clocks */
#define WASI_CLOCK_REALTIME 0
#define WASI_CLOCK_MONOTONIC 1
#define WASI_CLOCK_PROCESS_CPUTIME 2
#define WASI_CLOCK_THREAD_CPUTIME 3

/* WASI Filetype */
#define WASI_FILETYPE_UNKNOWN 0
#define WASI_FILETYPE_BLOCK_DEVICE 1
#define WASI_FILETYPE_CHARACTER_DEVICE 2
#define WASI_FILETYPE_DIRECTORY 3
#define WASI_FILETYPE_REGULAR_FILE 4
#define WASI_FILETYPE_SOCKET_DGRAM 5
#define WASI_FILETYPE_SOCKET_STREAM 6
#define WASI_FILETYPE_SYMBOLIC_LINK 7

/* WASI Open Flags */
#define WASI_O_CREAT 1
#define WASI_O_DIRECTORY 2
#define WASI_O_EXCL 4
#define WASI_O_TRUNC 8

/* WASI Rights */
#define WASI_RIGHT_FD_DATASYNC (1ULL << 0)
#define WASI_RIGHT_FD_READ (1ULL << 1)
#define WASI_RIGHT_FD_SEEK (1ULL << 2)
#define WASI_RIGHT_FD_FDSTAT_SET_FLAGS (1ULL << 3)
#define WASI_RIGHT_FD_SYNC (1ULL << 4)
#define WASI_RIGHT_FD_TELL (1ULL << 5)
#define WASI_RIGHT_FD_WRITE (1ULL << 6)
#define WASI_RIGHT_FD_ADVISE (1ULL << 7)
#define WASI_RIGHT_FD_ALLOCATE (1ULL << 8)
#define WASI_RIGHT_PATH_CREATE_DIRECTORY (1ULL << 9)
#define WASI_RIGHT_PATH_CREATE_FILE (1ULL << 10)
#define WASI_RIGHT_PATH_LINK_SOURCE (1ULL << 11)
#define WASI_RIGHT_PATH_LINK_TARGET (1ULL << 12)
#define WASI_RIGHT_PATH_OPEN (1ULL << 13)
#define WASI_RIGHT_FD_READDIR (1ULL << 14)
#define WASI_RIGHT_PATH_READLINK (1ULL << 15)
#define WASI_RIGHT_PATH_RENAME_SOURCE (1ULL << 16)
#define WASI_RIGHT_PATH_RENAME_TARGET (1ULL << 17)
#define WASI_RIGHT_PATH_FILESTAT_GET (1ULL << 18)
#define WASI_RIGHT_PATH_FILESTAT_SET_SIZE (1ULL << 19)
#define WASI_RIGHT_PATH_FILESTAT_SET_TIMES (1ULL << 20)
#define WASI_RIGHT_FD_FILESTAT_GET (1ULL << 21)
#define WASI_RIGHT_FD_FILESTAT_SET_SIZE (1ULL << 22)
#define WASI_RIGHT_FD_FILESTAT_SET_TIMES (1ULL << 23)
#define WASI_RIGHT_PATH_SYMLINK (1ULL << 24)
#define WASI_RIGHT_PATH_REMOVE_DIRECTORY (1ULL << 25)
#define WASI_RIGHT_PATH_UNLINK_FILE (1ULL << 26)
#define WASI_RIGHT_POLL_FD_READWRITE (1ULL << 27)
#define WASI_RIGHT_SOCK_SHUTDOWN (1ULL << 28)
#define WASI_RIGHT_SOCK_ACCEPT (1ULL << 29)

#define WASI_RIGHTS_ALL ((uint64_t)-1)

/* WASI Backends */
#define WASI_BACKEND_NATIVE 0
#define WASI_BACKEND_POSIX 1
#define WASI_BACKEND_IPC 2

/* WASI RUMP IO Max */
#define WASI_RUMP_IO_MAX 1024

/* WASI Errno */
#define WASI_ERRNO_SUCCESS 0
#define WASI_ERRNO_2BIG 1
#define WASI_ERRNO_ACCES 2
#define WASI_ERRNO_ADDRINUSE 3
#define WASI_ERRNO_ADDRNOTAVAIL 4
#define WASI_ERRNO_AFNOSUPPORT 5
#define WASI_ERRNO_AGAIN 6
#define WASI_ERRNO_ALREADY 7
#define WASI_ERRNO_BADF 8
#define WASI_ERRNO_BADMSG 9
#define WASI_ERRNO_BUSY 10
#define WASI_ERRNO_CANCELED 11
#define WASI_ERRNO_CHILD 12
#define WASI_ERRNO_CONNABORTED 13
#define WASI_ERRNO_CONNREFUSED 14
#define WASI_ERRNO_CONNRESET 15
#define WASI_ERRNO_DEADLK 16
#define WASI_ERRNO_DESTADDRREQ 17
#define WASI_ERRNO_DOM 18
#define WASI_ERRNO_DQUOT 19
#define WASI_ERRNO_EXIST 20
#define WASI_ERRNO_FAULT 21
#define WASI_ERRNO_FBIG 22
#define WASI_ERRNO_HOSTUNREACH 23
#define WASI_ERRNO_IDRM 24
#define WASI_ERRNO_ILSEQ 25
#define WASI_ERRNO_INPROGRESS 26
#define WASI_ERRNO_INTR 27
#define WASI_ERRNO_INVAL 28
#define WASI_ERRNO_IO 29
#define WASI_ERRNO_ISCONN 30
#define WASI_ERRNO_ISDIR 31
#define WASI_ERRNO_LOOP 32
#define WASI_ERRNO_MFILE 33
#define WASI_ERRNO_MLINK 34
#define WASI_ERRNO_MSGSIZE 35
#define WASI_ERRNO_MULTIHOP 36
#define WASI_ERRNO_NAMETOOLONG 37
#define WASI_ERRNO_NETDOWN 38
#define WASI_ERRNO_NETRESET 39
#define WASI_ERRNO_NETUNREACH 40
#define WASI_ERRNO_NFILE 41
#define WASI_ERRNO_NOBUFS 42
#define WASI_ERRNO_NODEV 43
#define WASI_ERRNO_NOENT 44
#define WASI_ERRNO_NOEXEC 45
#define WASI_ERRNO_NOLCK 46
#define WASI_ERRNO_NOLINK 47
#define WASI_ERRNO_NOMEM 48
#define WASI_ERRNO_NOMSG 49
#define WASI_ERRNO_NOPROTOOPT 50
#define WASI_ERRNO_NOSPC 51
#define WASI_ERRNO_NOSYS 52
#define WASI_ERRNO_NOTCONN 53
#define WASI_ERRNO_NOTDIR 54
#define WASI_ERRNO_NOTEMPTY 55
#define WASI_ERRNO_NOTRECOVERABLE 56
#define WASI_ERRNO_NOTSOCK 57
#define WASI_ERRNO_NOTSUP 58
#define WASI_ERRNO_NOTTY 59
#define WASI_ERRNO_NXIO 60
#define WASI_ERRNO_OVERFLOW 61
#define WASI_ERRNO_OWNERDEAD 62
#define WASI_ERRNO_PERM 63
#define WASI_ERRNO_PIPE 64
#define WASI_ERRNO_PROTO 65
#define WASI_ERRNO_PROTONOSUPPORT 66
#define WASI_ERRNO_PROTOTYPE 67
#define WASI_ERRNO_RANGE 68
#define WASI_ERRNO_ROFS 69
#define WASI_ERRNO_SPIPE 70
#define WASI_ERRNO_SRCH 71
#define WASI_ERRNO_STALE 72
#define WASI_ERRNO_TIMEDOUT 73
#define WASI_ERRNO_TXTBSY 74
#define WASI_ERRNO_XDEV 75
#define WASI_ERRNO_NOTCAPABLE 76

#endif /* WASI_CONSTANTS_H */
