<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <NoStdLib>true</NoStdLib>
    <NoConfig>true</NoConfig>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Lux9.CoreLib">
      <HintPath>../../corelib/bin/Release/net9.0/Lux9.CoreLib.dll</HintPath>
    </Reference>
    <Reference Include="Lux9.FSharp">
      <HintPath>../../fsharp/bin/Release/net9.0/Lux9.FSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
