/*
 * Minimal TPM2 SAPI/Marshaling - From Scratch
 *
 * Implements only what we need:
 * - TPM2_Create (for sealing)
 * - TPM2_Unseal
 * - Basic marshaling (big-endian encoding)
 *
 * Why from scratch instead of TSS2 library?
 * - TSS2 has 29k LOC with tons of standard library dependencies
 * - We only need ~300 lines for our use case
 * - Simpler to write clean code than fix library conflicts
 */

#include "u.h"
#include "portlib.h"
#include "mem.h"
#include "dat.h"
#include "fns.h"

/* External TIS driver function */
extern int tpm_transmit(u8int *cmd, usize cmd_len, u8int *resp, usize *resp_len);

/* TPM 2.0 Constants */
#define TPM2_ST_NO_SESSIONS     0x8001
#define TPM2_ST_SESSIONS        0x8002

#define TPM2_CC_CreatePrimary   0x00000131
#define TPM2_CC_Create          0x00000153
#define TPM2_CC_Load            0x00000157
#define TPM2_CC_Unseal          0x0000015E

#define TPM2_RH_OWNER           0x40000001
#define TPM2_RH_NULL            0x40000007

#define TPM2_ALG_SHA256         0x000B
#define TPM2_ALG_KEYEDHASH      0x0008
#define TPM2_ALG_NULL           0x0010

#define TPM_SUCCESS             0x00000000

/* Marshaling Helpers - Big Endian */

static void
marshal_u16(u8int **buf, u16int val)
{
	(*buf)[0] = (val >> 8) & 0xFF;
	(*buf)[1] = val & 0xFF;
	*buf += 2;
}

static void
marshal_u32(u8int **buf, u32int val)
{
	(*buf)[0] = (val >> 24) & 0xFF;
	(*buf)[1] = (val >> 16) & 0xFF;
	(*buf)[2] = (val >> 8) & 0xFF;
	(*buf)[3] = val & 0xFF;
	*buf += 4;
}

static u16int
unmarshal_u16(u8int **buf)
{
	u16int val = ((*buf)[0] << 8) | (*buf)[1];
	*buf += 2;
	return val;
}

static u32int
unmarshal_u32(u8int **buf)
{
	u32int val = ((*buf)[0] << 24) | ((*buf)[1] << 16) |
	             ((*buf)[2] << 8) | (*buf)[3];
	*buf += 4;
	return val;
}

/* Marshal TPM2B buffer (size + data) */
static void
marshal_tpm2b(u8int **buf, u8int *data, u16int len)
{
	marshal_u16(buf, len);
	if(len > 0){
		memmove(*buf, data, len);
		*buf += len;
	}
}

/* Unmarshal TPM2B buffer */
static u16int
unmarshal_tpm2b(u8int **buf, u8int *data, u16int max_len)
{
	u16int len = unmarshal_u16(buf);
	if(len > max_len)
		return 0;
	if(len > 0){
		memmove(data, *buf, len);
		*buf += len;
	}
	return len;
}

/*
 * TPM2_CreatePrimary - Create Storage Root Key (SRK)
 *
 * Returns handle to primary key (parent for sealed objects)
 */
int
tpm2_create_primary(u32int *handle_out)
{
	u8int cmd[256];
	u8int resp[256];
	usize resp_len = sizeof(resp);
	u8int *p = cmd;
	u8int *rp;
	u32int rc;

	/* Command Header */
	marshal_u16(&p, TPM2_ST_NO_SESSIONS);  /* tag */
	marshal_u32(&p, 0);  /* size - fill later */
	marshal_u32(&p, TPM2_CC_CreatePrimary);  /* command code */

	/* Primary Handle (owner hierarchy) */
	marshal_u32(&p, TPM2_RH_OWNER);

	/* Auth (empty - no password) */
	marshal_u32(&p, 0);  /* authSize = 0 */

	/* inSensitive (empty - no sensitive data for SRK) */
	marshal_u16(&p, 0);  /* size = 0 */

	/* inPublic - RSA 2048 storage key template */
	u8int *public_start = p;
	marshal_u16(&p, 0);  /* size - fill later */

	/* TPMT_PUBLIC */
	marshal_u16(&p, TPM2_ALG_SHA256);  /* type = RSA */
	marshal_u16(&p, TPM2_ALG_SHA256);  /* nameAlg */
	marshal_u32(&p, 0x00030072);  /* objectAttributes */
	marshal_u16(&p, 0);  /* authPolicy size */

	/* RSA parameters */
	marshal_u16(&p, TPM2_ALG_NULL);  /* symmetric */
	marshal_u16(&p, TPM2_ALG_NULL);  /* scheme */
	marshal_u16(&p, 2048);  /* keyBits */
	marshal_u32(&p, 0);  /* exponent (0 = default 65537) */
	marshal_u16(&p, 0);  /* unique size (generated by TPM) */

	/* Fill in public size */
	u16int public_size = p - public_start - 2;
	public_start[0] = (public_size >> 8) & 0xFF;
	public_start[1] = public_size & 0xFF;

	/* outsideInfo (empty) */
	marshal_u16(&p, 0);

	/* creationPCR (empty) */
	marshal_u32(&p, 0);

	/* Fill in command size */
	u32int cmd_size = p - cmd;
	cmd[2] = (cmd_size >> 24) & 0xFF;
	cmd[3] = (cmd_size >> 16) & 0xFF;
	cmd[4] = (cmd_size >> 8) & 0xFF;
	cmd[5] = cmd_size & 0xFF;

	/* Send command */
	if(tpm_transmit(cmd, cmd_size, resp, &resp_len) < 0){
		print("tpm2_create_primary: transmit failed\n");
		return -1;
	}

	/* Parse response */
	rp = resp;
	unmarshal_u16(&rp);  /* tag */
	unmarshal_u32(&rp);  /* size */
	rc = unmarshal_u32(&rp);  /* response code */

	if(rc != TPM_SUCCESS){
		print("tpm2_create_primary: TPM returned error 0x%08X\n", rc);
		return -1;
	}

	/* Extract handle */
	*handle_out = unmarshal_u32(&rp);

	print("tpm2_create_primary: Created SRK with handle 0x%08X\n", *handle_out);
	return 0;
}

/*
 * TPM2_Create - Create sealed data object
 *
 * Seals data under parent key. Data can only be unsealed if PCRs match.
 */
int
tpm2_create(u32int parent_handle, u8int *data, u16int data_len,
            u8int *private_out, u16int *private_len,
            u8int *public_out, u16int *public_len)
{
	u8int cmd[512];
	u8int resp[512];
	usize resp_len = sizeof(resp);
	u8int *p = cmd;
	u8int *rp;
	u32int rc;

	if(data_len > 128){
		print("tpm2_create: data too large (%d bytes, max 128)\n", data_len);
		return -1;
	}

	/* Command Header */
	marshal_u16(&p, TPM2_ST_NO_SESSIONS);
	marshal_u32(&p, 0);  /* size - fill later */
	marshal_u32(&p, TPM2_CC_Create);

	/* Parent handle */
	marshal_u32(&p, parent_handle);

	/* Auth (empty) */
	marshal_u32(&p, 0);

	/* inSensitive - contains the data to seal */
	u8int *sens_start = p;
	marshal_u16(&p, 0);  /* size - fill later */
	marshal_u16(&p, 0);  /* userAuth size (no password) */
	marshal_tpm2b(&p, data, data_len);  /* sensitive data */

	u16int sens_size = p - sens_start - 2;
	sens_start[0] = (sens_size >> 8) & 0xFF;
	sens_start[1] = sens_size & 0xFF;

	/* inPublic - keyedhash object (sealed data) */
	u8int *public_start = p;
	marshal_u16(&p, 0);  /* size - fill later */

	marshal_u16(&p, TPM2_ALG_KEYEDHASH);  /* type */
	marshal_u16(&p, TPM2_ALG_SHA256);  /* nameAlg */
	marshal_u32(&p, 0x00040002);  /* objectAttributes (fixedTPM | fixedParent) */
	marshal_u16(&p, 0);  /* authPolicy size */

	/* KEYEDHASH parameters */
	marshal_u16(&p, TPM2_ALG_NULL);  /* scheme */
	marshal_u16(&p, 0);  /* unique size */

	u16int public_size = p - public_start - 2;
	public_start[0] = (public_size >> 8) & 0xFF;
	public_start[1] = public_size & 0xFF;

	/* outsideInfo (empty) */
	marshal_u16(&p, 0);

	/* creationPCR (empty - not sealing to PCRs yet) */
	marshal_u32(&p, 0);

	/* Fill command size */
	u32int cmd_size = p - cmd;
	cmd[2] = (cmd_size >> 24) & 0xFF;
	cmd[3] = (cmd_size >> 16) & 0xFF;
	cmd[4] = (cmd_size >> 8) & 0xFF;
	cmd[5] = cmd_size & 0xFF;

	/* Send command */
	if(tpm_transmit(cmd, cmd_size, resp, &resp_len) < 0){
		print("tpm2_create: transmit failed\n");
		return -1;
	}

	/* Parse response */
	rp = resp;
	unmarshal_u16(&rp);  /* tag */
	unmarshal_u32(&rp);  /* size */
	rc = unmarshal_u32(&rp);

	if(rc != TPM_SUCCESS){
		print("tpm2_create: TPM returned error 0x%08X\n", rc);
		return -1;
	}

	/* Extract private and public blobs */
	*private_len = unmarshal_tpm2b(&rp, private_out, 256);
	*public_len = unmarshal_tpm2b(&rp, public_out, 256);

	print("tpm2_create: Created sealed object (priv=%d, pub=%d bytes)\n",
	      *private_len, *public_len);
	return 0;
}

/*
 * TPM2_Load - Load sealed object into TPM
 *
 * Returns handle to loaded object
 */
int
tpm2_load(u32int parent_handle, u8int *private_blob, u16int private_len,
          u8int *public_blob, u16int public_len, u32int *handle_out)
{
	u8int cmd[512];
	u8int resp[256];
	usize resp_len = sizeof(resp);
	u8int *p = cmd;
	u8int *rp;
	u32int rc;

	/* Command Header */
	marshal_u16(&p, TPM2_ST_NO_SESSIONS);
	marshal_u32(&p, 0);  /* size - fill later */
	marshal_u32(&p, TPM2_CC_Load);

	/* Parent handle */
	marshal_u32(&p, parent_handle);

	/* Auth (empty) */
	marshal_u32(&p, 0);

	/* Private blob */
	marshal_tpm2b(&p, private_blob, private_len);

	/* Public blob */
	marshal_tpm2b(&p, public_blob, public_len);

	/* Fill command size */
	u32int cmd_size = p - cmd;
	cmd[2] = (cmd_size >> 24) & 0xFF;
	cmd[3] = (cmd_size >> 16) & 0xFF;
	cmd[4] = (cmd_size >> 8) & 0xFF;
	cmd[5] = cmd_size & 0xFF;

	/* Send command */
	if(tpm_transmit(cmd, cmd_size, resp, &resp_len) < 0){
		print("tpm2_load: transmit failed\n");
		return -1;
	}

	/* Parse response */
	rp = resp;
	unmarshal_u16(&rp);  /* tag */
	unmarshal_u32(&rp);  /* size */
	rc = unmarshal_u32(&rp);

	if(rc != TPM_SUCCESS){
		print("tpm2_load: TPM returned error 0x%08X\n", rc);
		return -1;
	}

	/* Extract handle */
	*handle_out = unmarshal_u32(&rp);

	print("tpm2_load: Loaded object with handle 0x%08X\n", *handle_out);
	return 0;
}

/*
 * TPM2_Unseal - Unseal data from loaded object
 */
int
tpm2_unseal(u32int item_handle, u8int *data_out, u16int *data_len)
{
	u8int cmd[128];
	u8int resp[256];
	usize resp_len = sizeof(resp);
	u8int *p = cmd;
	u8int *rp;
	u32int rc;

	/* Command Header */
	marshal_u16(&p, TPM2_ST_NO_SESSIONS);
	marshal_u32(&p, 0);  /* size - fill later */
	marshal_u32(&p, TPM2_CC_Unseal);

	/* Item handle */
	marshal_u32(&p, item_handle);

	/* Auth (empty) */
	marshal_u32(&p, 0);

	/* Fill command size */
	u32int cmd_size = p - cmd;
	cmd[2] = (cmd_size >> 24) & 0xFF;
	cmd[3] = (cmd_size >> 16) & 0xFF;
	cmd[4] = (cmd_size >> 8) & 0xFF;
	cmd[5] = cmd_size & 0xFF;

	/* Send command */
	if(tpm_transmit(cmd, cmd_size, resp, &resp_len) < 0){
		print("tpm2_unseal: transmit failed\n");
		return -1;
	}

	/* Parse response */
	rp = resp;
	unmarshal_u16(&rp);  /* tag */
	unmarshal_u32(&rp);  /* size */
	rc = unmarshal_u32(&rp);

	if(rc != TPM_SUCCESS){
		print("tpm2_unseal: TPM returned error 0x%08X\n", rc);
		return -1;
	}

	/* Skip parameter size */
	unmarshal_u32(&rp);

	/* Extract unsealed data */
	*data_len = unmarshal_tpm2b(&rp, data_out, 128);

	print("tpm2_unseal: Unsealed %d bytes\n", *data_len);
	return 0;
}
