</$objtype/mkfile

TARG=cmdexec
OFILES=cmdexec.$O
HFILES=
BIN=$home/bin/$objtype

# Link with lib9p, libthread for 9P filesystem, and libip for network functions
LDFLAGS=$LDFLAGS -l9p -lthread -lip

</sys/src/cmd/mkone

clean:V:
	rm -f *.$O $O.out *.acid $TARG $CLEANFILES

nuke:V: clean
	rm -f $BIN/$TARG