/*
 * Sartfs Storage Engine - Core Data Types
 *
 * Sophia Adaptive Radix Tree Filesystem
 * Immutable, content-addressed storage for Lux9 microkernel
 *
 * Philosophy:
 *   1. Immutability: "Update is Recreation"
 *   2. Identity: UUIDv8 = Hash(RecordData)
 *   3. Persistence: Journal is source of truth
 */

#ifndef SART_DAT_H
#define SART_DAT_H
#define DMDIR 0x80000000

/*
 * Plan 9 / Lux9 Type Compatibility Layer
 *
 * These definitions ensure HJFS headers compile in our environment.
 * We don't use the threading types (Channel, QLock, etc.) since
 * Sartfs operates in single-threaded synchronous mode.
 */

#ifndef _LIBLUX_H_
/* Basic integer types */
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef unsigned long long uvlong;
typedef long long vlong;

typedef unsigned char u8int;
typedef unsigned short u16int;
typedef unsigned int u32int;
typedef unsigned long long u64int;

/* Nil pointer */
#define nil ((void *)0)

/* Qid - Plan 9 unique file identifier */
typedef struct Qid {
  uvlong path;
  ulong vers;
  uchar type;
} Qid;
#endif

/* Dir - Plan 9 directory entry (minimal) */
#ifndef _DIR_H_
#define _DIR_H_
typedef struct Dir {
  ushort type;
  uint dev;
  Qid qid;
  ulong mode;
  ulong atime;
  ulong mtime;
  vlong length;
  char *name;
  char *uid;
  char *gid;
  char *muid;
} Dir;
#endif

/* Threading stubs - not used in synchronous Sartfs */
typedef struct {
  int val;
} QLock;
typedef struct {
  QLock *l;
} Rendez;
typedef struct {
  int readers;
  int writer;
} RWLock;
typedef struct {
  int dummy;
} Channel;

/* Include HJFS block-level types */
#include "hjfs_dat.h"

/*
 * UUIDv8 - Content-Addressed Identity
 *
 * Generated by hashing RecordData.
 * RFC 9562 compliant (version 8, variant 10xx).
 * Compatible with kernel uuid_t.
 */
typedef struct UUIDv8 {
  u8int data[16]; /* 128-bit UUID */
} UUIDv8;

/*
 * RecordData - File Metadata
 *
 * Contains all metadata needed to identify and locate a file.
 * Extended with delta compression and TLSH semantic clustering.
 *
 * Size considerations:
 * - Core: 80 bytes (addresses, hashes, times)
 * - Delta: 46 bytes (base UUID, version chain, timestamps)
 * - TLSH: 35 bytes (fuzzy similarity)
 * - Reserved: 7 bytes
 * Total: ~168 bytes per file (optimized for space)
 */
typedef struct RecordData {
  /* Core metadata */
  u64int block_addr;   /* Physical Block Address (8 bytes) */
  u8int data_hash[32]; /* BLAKE3 Hash of content (32 bytes) - exact match */
  u64int size;         /* Logical size (8 bytes) */
  u32int perms;        /* Permissions (4 bytes) */
  u64int atime;        /* Access time (8 bytes) */
  u64int mtime;        /* Modification time (8 bytes) */

  /* Delta Compression Fields - 46 bytes total */
  u8int type;          /* 0=FULL, 1=DELTA (1 byte) */
  u8int delta_format;  /* 0=none, 1=xdelta3, 2=bsdiff, 3=RLE (1 byte) */
  u32int delta_size;   /* Size of delta data (4 bytes) */
  UUIDv8 base_uuid;    /* Base object UUID for delta (16 bytes) */
  UUIDv8 prev_version; /* Previous version UUID - history chain (16 bytes) */
  u64int version;      /* Monotonic version counter (8 bytes) */

  /* TLSH Fuzzy Hashing - 35 bytes (compact!) */
  u8int tlsh[35]; /* Trend Micro LSH for similarity clustering */

  /* Optimization fields */
  u32int write_timestamp; /* Reduced from u64 - 32-bit seconds since epoch */
  u16int chain_depth;     /* Reduced from u32 - max 65K chain depth */

  u8int _reserved[7]; /* Future extensions */
} RecordData;

/* RecordData total size: ~168 bytes
 * Compare to alternatives:
 * - With MinHash (128 hashes): ~240 bytes (42% larger)
 * - With both TLSH+MinHash: ~275 bytes (63% larger)
 *
 * For 10K files:
 * - This design: 1.68 MB
 * - MinHash: 2.4 MB
 * - Both: 2.75 MB
 *
 * Storage tax per file: 168 bytes (acceptable)
 */

/*
 * Journal Entry Types
 */
typedef enum {
  JENT_BLOB = 0, /* Content registration (UUID -> RecordData) */
  JENT_EDGE = 1  /* Namespace edge (Parent + Name -> Child) */
} JournalEntryType;

/*
 * EdgeRecord - Namespace Relationship
 *
 * Maps a name within a parent directory to a child object.
 */
typedef struct EdgeRecord {
  UUIDv8 parent_id; /* UUID of the parent directory */
  UUIDv8 child_id;  /* UUID of the child object (file or dir) */
  char name[128];   /* Name of the entry in the directory */
} EdgeRecord;

/*
 * JournalEntry - Persistent Log Record
 *
 * Each entry represents a single atomic update to the system.
 */
typedef struct JournalEntry {
  u32int magic;     /* Entry magic: SART_ENTRY_MAGIC */
  u16int type;      /* JournalEntryType */
  u16int version;   /* Entry format version */
  u64int timestamp; /* Creation time (nsec) */
  union {
    struct {
      UUIDv8 id;
      RecordData rec;
    } blob;
    EdgeRecord edge;
  } u;
  u64int checksum; /* XOR fold integrity check */
} JournalEntry;

/*
 * SartStore - In-Memory Storage Context
 *
 * Holds file descriptors and state for the storage engine.
 */
typedef struct SartStore {
  int disk_fd;         /* Raw disk file descriptor */
  int journal_fd;      /* Journal file descriptor */
  u64int disk_base;    /* Base offset for disk region */
  u64int journal_base; /* Base offset for journal region */
  u64int journal_pos;  /* Current journal write offset */
  u64int next_block;   /* Next free block address */
  u64int total_blocks; /* Total blocks on disk */
  u64int entry_count;  /* Number of journal entries */
} SartStore;

/* Magic numbers */
#define SART_JOURNAL_MAGIC 0x53415254 /* "SART" */
#define SART_ENTRY_MAGIC 0x454E5452   /* "ENTR" */
#define SART_VERSION 1

/* Block size (from HJFS) */
#define SART_BLOCK_SIZE BLOCK /* 4096 bytes */

/* Journal header (first block of journal file) */
typedef struct JournalHeader {
  u32int magic;       /* SART_JOURNAL_MAGIC */
  u32int version;     /* Format version */
  u64int entry_count; /* Total entries in journal */
  u64int first_entry; /* Offset of first entry */
  u64int last_entry;  /* Offset of last entry */
  u8int reserved[SART_BLOCK_SIZE - 32];
} JournalHeader;

/* Helper macros */
#define UUID_EQUAL(a, b) (memcmp((a)->data, (b)->data, 16) == 0)

#define UUID_CLEAR(u) memset((u)->data, 0, 16)

/* Error codes */
#define SART_OK 0
#define SART_ERR_IO -1
#define SART_ERR_CORRUPT -2
#define SART_ERR_NOMEM -3
#define SART_ERR_NOTFOUND -4
#define SART_ERR_FULL -5

void sart_set_backing_offsets(u64int disk_base, u64int journal_base);

#endif /* SART_DAT_H */
