# Service Registry Configuration
# Name          Path                Critical  AutoRestart  Hash
hal_server      /boot/hal_server    1         1            -
file_server     /boot/file_server   0         1            -
wasm_server     /boot/wasm_server   1         1            -
fakeserver      /boot/fakeserver    0         1            -
