/* il2native.c - CLR AOT Compiler Tool
 *
 * Compiles a .NET DLL into QBE Intermediate Language (IL) using the
 * kernel CLR components (il_parser, il_to_fruity, fruity_to_qbe).
 *
 * Capabilities:
 * 1. Parses .NET DLL
 * 2. Generates QBE IL for all methods with bodies
 * 3. Detects internal calls and generates assembly aliases in bindings.s
 *
 * Usage:
 *   ./il2native <input.dll> <output.ssa> <bindings.s>
 */

#define _GNU_SOURCE
#include "il_parser.h"
#include <ctype.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Mock kernel environment for CLR components
#define USERSPACE_TEST 1
#define KERNEL                                                                 \
  1 // Cheat to avoid printf redefinition issues if guarding on KERNEL

// Type definitions expected by kernel headers
typedef uint8_t u8int;
typedef uint16_t u16int;
typedef uint32_t u32int;
typedef uint64_t u64int;
typedef size_t usize;
typedef uintptr_t uintptr;
#define nil NULL

// Kernel macros
#define KADDR(x) ((void *)(x))
#define PADDR(x) ((uintptr)(x))
#define snprint snprintf

// Include CLR headers
// We need to disable KERNEL definition for headers if they use it to hide
// things
#undef KERNEL
#include "../kernel/clr/fruity/fruity_to_qbe.h"
#include "../kernel/clr/il_parser.h"
#include "../kernel/clr/il_to_fruity.h"

// MethodImpl flags
#define METHOD_IMPL_INTERNAL_CALL 0x1000

// Internal Call Mapping Table
typedef struct {
  const char *TypeName;
  const char *MethodName;
  const char *NativeSymbol;
} InternalCallMap;

static InternalCallMap InternalCalls[] = {
    // System.P9.P9Internal
    {"System.P9.P9Internal", "Attach", "clr_p9_attach"},
    {"System.P9.P9Internal", "Read", "clr_p9_read"},
    {"System.P9.P9Internal", "Write", "clr_p9_write"},
    {"System.P9.P9Internal", "Clunk", "clr_p9_clunk"},
    {"System.P9.P9Internal", "Stat", "clr_p9_stat"},

    // Init Direct Calls
    {"Init", "Write", "clr_write"},

    // Core BCL
    {"System.String", "get_Length", "clr_string_get_length"},
    {"System.Threading.Thread", "get_CurrentThread", "clr_thread_get_current"},

    // Future mappings
    {NULL, NULL, NULL}};

const char *find_native_symbol(const char *type, const char *method) {
  for (int i = 0; InternalCalls[i].TypeName != NULL; i++) {
    if (strcmp(InternalCalls[i].TypeName, type) == 0 &&
        strcmp(InternalCalls[i].MethodName, method) == 0) {
      return InternalCalls[i].NativeSymbol;
    }
  }
  return NULL;
}

// Clean method name for assembly labels (replace special chars)
void normalize_name(char *dest, const char *src) {
  while (*src) {
    if (isalnum(*src) || *src == '_') {
      *dest++ = *src;
    } else {
      *dest++ = '_';
    }
    src++;
  }
  *dest = 0;
}

int main(int argc, char **argv) {
  if (argc != 4) {
    fprintf(stderr, "Usage: %s <input.dll> <output.ssa> <bindings.s>\n",
            argv[0]);
    return 1;
  }

  const char *input_path = argv[1];
  const char *output_ssa_path = argv[2];
  const char *bindings_path = argv[3];

  // 1. Parse Assembly
  il_error_t error;
  il_assembly_t *assembly = il_parse_assembly(input_path, &error);
  if (!assembly) {
    fprintf(stderr, "Error parsing assembly: %s\n", il_error_string(error));
    return 1;
  }
  printf("Parsed assembly: %zu methods\n", assembly->method_count);

  // Prepare Output Files
  FILE *f_ssa = fopen(output_ssa_path, "w");
  if (!f_ssa) {
    perror("fopen ssa");
    return 1;
  }

  FILE *f_bind = fopen(bindings_path, "w");
  if (!f_bind) {
    perror("fopen bindings");
    return 1;
  }

  fprintf(f_bind, "# Internal Call Bindings generated by il2native\n");
  fprintf(f_bind, ".text\n");

  // Emit entry point stub
  if (assembly->cli_header.entry_point_token) {
    printf("Entry Point: %08x\n", assembly->cli_header.entry_point_token);
    fprintf(f_bind, ".global main\n");
    fprintf(f_bind, "main:\n");
    fprintf(f_bind, "  call method_%u\n",
            assembly->cli_header.entry_point_token);
    fprintf(f_bind, "  ret\n");
  }

  // Initialize Fruity Module
  fruity_module_t module = {0};
  module.functions_head = NULL;
  fruity_function_t *last_func = NULL;

  // 2. Iterate Methods
  uint32_t method_count = assembly->tables_header.row_counts[TABLE_METHODDEF];
  printf("Methods found in table: %u\n", method_count);

  // Dump MemberRefs (0x0A)
  uint32_t memberref_count = assembly->tables_header.row_counts[0x0A];
  printf("MemberRefs found: %u\n", memberref_count);
  for (uint32_t rid = 1; rid <= memberref_count; rid++) {
    memberref_row_t *row = il_get_memberref(assembly, rid);
    if (row) {
      const char *name = il_get_string(assembly, row->name_index);
      uint32_t token = (0x0A << 24) | rid;
      printf("MemberRef: %s (Token: %08x)\n", name ? name : "<unknown>", token);
      free(row);
    }
  }

  // 2. Reachability Traversal (Tree Shaking)
  // Instead of compiling all methods, we start from EntryPoint and follow
  // calls.

  uint32_t *queue =
      malloc(sizeof(uint32_t) * (method_count + 1024)); // Plenty of space
  uint8_t *visited = calloc(method_count + 1, 1);
  int head = 0;
  int tail = 0;

  // Start with EntryPoint
  uint32_t entry_token = assembly->cli_header.entry_point_token;
  if (entry_token == 0) {
    // Fallback: Find "Main"
    // For now, assume Method 1 is entry if not specified, or scan.
    // But Init.dll has EntryPointToken set typically.
    entry_token = 0x06000005; // HACK: From detailed log if needed, but try
                              // finding it? Better: Scan for "Main" if 0.
  }

  // Verify EntryPoint token validity
  if ((entry_token >> 24) == TABLE_METHODDEF) {
    uint32_t rid = entry_token & 0x00FFFFFF;
    if (rid > 0 && rid <= method_count) {
      queue[tail++] = entry_token;
      visited[rid] = 1;
      printf("Root: %08x\n", entry_token);
    }
  }

  // Also add any InternalCalls we want to force? No, only reachable.
  // Actually, if we have specific exports, add them.
  // But Init.Write is called by Main, so it will be found.

  while (head < tail) {
    uint32_t token = queue[head++];

    il_method_t *method = il_get_method_by_token(assembly, token);
    if (!method) {
      fprintf(stderr, "Warning: Failed to load method token %08x\n", token);
      continue;
    }
    printf("Processing: %s (Token: %08x)\n", method->name, token);

    // Check for InternalCall
    if (method->impl_flags & METHOD_IMPL_INTERNAL_CALL) {
      const char *parent_type =
          il_get_method_parent_type_name(assembly, method->method_token);
      const char *native = find_native_symbol(
          parent_type ? parent_type : "Init", method->name); // Hack fallback

      if (native) {
        fprintf(f_bind, ".global method_%u\n", method->method_token);
        fprintf(f_bind, "method_%u:\n", method->method_token);
        fprintf(f_bind, "  jmp %s\n", native);
        printf("Bound method_%u -> %s\n", method->method_token, native);
      } else {
        fprintf(stderr, "WARNING: Unbound InternalCall: %s::%s\n", parent_type,
                method->name);
        fprintf(f_bind, ".global method_%u\n", method->method_token);
        fprintf(f_bind, "method_%u:\n", method->method_token);
        fprintf(f_bind, "  ud2\n");
      }
      // Internal call has no body to scan
      continue;
    }

    // Convert to Fruity
    if (method->il_code && method->il_code_size > 0) {
      il_to_fruity_error_t f_err;
      fruity_function_t *func =
          il_to_fruity_convert_method(assembly, method, &f_err);
      if (!func) {
        fprintf(stderr, "Error converting method %s (Token %08x): %d\n",
                method->name, method->method_token, f_err);
        continue;
      }

      // Name and Append
      char name_buf[64];
      snprintf(name_buf, sizeof(name_buf), "method_%u", method->method_token);
      func->name = strdup(name_buf);

      if (!last_func) {
        module.functions_head = func;
      } else {
        last_func->next = func;
      }
      last_func = func;

      // SCAN instructions for calls
      fruity_basic_block_t *bb = func->blocks_head;
      while (bb) {
        fruity_instruction_t *instr = bb->instructions_head;
        while (instr) {
          if (instr->opcode == FRUITY_CALL || instr->opcode == FRUITY_NEWOBJ ||
              instr->opcode == FRUITY_LDFTN) {
            if (instr->operand.type == FRUITY_OP_METHOD) {
              uint32_t target = instr->operand.value.token;
              if ((target >> 24) == TABLE_METHODDEF) {
                uint32_t rid = target & 0x00FFFFFF;
                if (rid > 0 && rid <= method_count && !visited[rid]) {
                  visited[rid] = 1;
                  queue[tail++] = target;
                  // printf("  Queueing: %08x\n", target);
                }
              }
            }
          }
          instr = instr->next;
        }
        bb = bb->next;
      }
    }
  }

  // 3. Convert Module to QBE SSA
  // We allocate a large buffer for output
  size_t out_size = 1024 * 1024 * 16; // 16MB
  void *out_buf = malloc(out_size);
  if (!out_buf) {
    perror("malloc");
    return 1;
  }

  char qbe_err[256];
  if (fruity_to_qbe(&module, (uintptr)out_buf, qbe_err, sizeof(qbe_err)) != 0) {
    fprintf(stderr, "QBE Generation Failed: %s\n", qbe_err);
    return 1;
  }

  // Write to file
  fprintf(f_ssa, "%s", (char *)out_buf);

  // Cleanup
  fclose(f_ssa);
  fclose(f_bind);
  // free... (skip for short lived tool)

  printf("Success! Generated %s and %s\n", output_ssa_path, bindings_path);
  return 0;
}
