<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <NoStdLib>true</NoStdLib>
    <NoConfig>true</NoConfig>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="FSharp.Core.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../bcl/src/System.Runtime/System.Runtime.csproj" />
  </ItemGroup>
</Project>
