/* lux9cc.c - Lux9 AOT Compiler
 *
 * Compiles .NET DLLs to native binaries for Lux9.
 *
 * Pipeline:
 *   .NET DLL → IL Parser → Fruity IR → QBE IL → QBE → Assembly → Binary
 *
 * Usage:
 *   lux9cc input.dll -o output.qbe   # Emit QBE IL
 *   lux9cc input.dll -o output.s     # Emit assembly (requires qbe)
 *   lux9cc input.dll -o output.o     # Emit object file
 *
 * Build:
 *   gcc -o lux9cc lux9cc.c il_parser.c il_disasm.c il_to_fruity.c \
 *       -I. -I./fruity -Wall -Wextra -O2
 */

#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "fruity/fruity_ir.h"
#include "il_disasm.h"
#include "il_parser.h"
#include "il_to_fruity.h"

/* Version info */
#define LUX9CC_VERSION "0.1.0"
#define LUX9CC_TARGET "lux9-x86_64"

/* Output format */
typedef enum {
  OUTPUT_QBE, /* QBE IL (.qbe) */
  OUTPUT_ASM, /* Assembly (.s) */
  OUTPUT_OBJ, /* Object file (.o) */
  OUTPUT_BIN, /* Binary executable */
  OUTPUT_IR,  /* Fruity IR dump (debug) */
} output_format_t;

/* Options */
typedef struct {
  const char *input_file;
  const char *output_file;
  output_format_t format;
  int verbose;
  int dump_il;
  int dump_ir;
  const char *entry_point;
} lux9cc_options_t;

/* Forward declarations */
static void print_usage(const char *prog);
static void print_version(void);
static output_format_t detect_format(const char *filename);
static int emit_qbe_header(FILE *out);
static int emit_qbe_function(FILE *out, fruity_function_t *func);
static int compile_assembly(lux9cc_options_t *opts, il_assembly_t *assembly);

/* Emit QBE IL header with runtime stubs */
static int emit_qbe_header(FILE *out) {
  fprintf(out, "# QBE IL generated by lux9cc %s\n", LUX9CC_VERSION);
  fprintf(out, "# Target: %s\n\n", LUX9CC_TARGET);

  /* Runtime function prototypes */
  fprintf(out, "# Lux9 Runtime Functions\n");
  fprintf(out, "export function l $lux_alloc(w %%size, w %%type) {\n");
  fprintf(out, "@start\n");
  fprintf(out, "    ret 0\n");
  fprintf(out, "}\n\n");

  fprintf(out, "export function $lux_print(l %%ptr) {\n");
  fprintf(out, "@start\n");
  fprintf(out, "    ret\n");
  fprintf(out, "}\n\n");

  return 0;
}

/* Emit a Fruity function as QBE IL */
static int emit_qbe_function(FILE *out, fruity_function_t *func) {
  fruity_basic_block_t *bb;
  fruity_instruction_t *instr;
  int tmp = 0;

  /* Function signature */
  fprintf(out, "export function w $%s(", func->name ? func->name : "anon");
  for (size_t i = 0; i < func->arg_count; i++) {
    fprintf(out, "%sl %%arg%zu", i == 0 ? "" : ", ", i);
  }
  fprintf(out, ") {\n");

  /* Local variables */
  for (size_t i = 0; i < func->local_count; i++) {
    fprintf(out, "    %%loc%zu =l alloc8 8\n", i);
  }

  fprintf(out, "@start\n");

  /* Emit basic blocks */
  for (bb = func->blocks_head; bb != NULL; bb = bb->next) {
    if (bb != func->blocks_head) {
      fprintf(out, "@bb%u\n", bb->block_id);
    }

    for (instr = bb->instructions_head; instr != NULL; instr = instr->next) {
      switch (instr->opcode) {
      case FRUITY_NOP:
        /* Skip */
        break;

      case FRUITY_LDC_I4:
        fprintf(out, "    %%t%d =w copy %d\n", ++tmp,
                (int)instr->operand.value.i64);
        break;

      case FRUITY_LDC_I8:
        fprintf(out, "    %%t%d =l copy %ld\n", ++tmp,
                instr->operand.value.i64);
        break;

      case FRUITY_LDNULL:
        fprintf(out, "    %%t%d =l copy 0\n", ++tmp);
        break;

      case FRUITY_DUP:
        fprintf(out, "    %%t%d =l copy %%t%d\n", tmp + 1, tmp);
        tmp++;
        break;

      case FRUITY_POP:
        tmp--;
        break;

      case FRUITY_LOAD_LOCAL:
        fprintf(out, "    %%t%d =l loadl %%loc%u\n", ++tmp,
                instr->operand.value.index);
        break;

      case FRUITY_STORE_LOCAL:
        fprintf(out, "    storel %%t%d, %%loc%u\n", tmp--,
                instr->operand.value.index);
        break;

      case FRUITY_LOAD_ARG:
        fprintf(out, "    %%t%d =l copy %%arg%u\n", ++tmp,
                instr->operand.value.index);
        break;

      case FRUITY_ADD:
        fprintf(out, "    %%t%d =w add %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_SUB:
        fprintf(out, "    %%t%d =w sub %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_MUL:
        fprintf(out, "    %%t%d =w mul %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_DIV:
        fprintf(out, "    %%t%d =w div %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_REM:
        fprintf(out, "    %%t%d =w rem %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_AND:
        fprintf(out, "    %%t%d =w and %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_OR:
        fprintf(out, "    %%t%d =w or %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_XOR:
        fprintf(out, "    %%t%d =w xor %%t%d, %%t%d\n", tmp - 1, tmp - 1, tmp);
        tmp--;
        break;

      case FRUITY_NEG:
        fprintf(out, "    %%t%d =w sub 0, %%t%d\n", tmp, tmp);
        break;

      case FRUITY_NOT:
        fprintf(out, "    %%t%d =w xor %%t%d, -1\n", tmp, tmp);
        break;

      case FRUITY_CALL:
        fprintf(out, "    %%t%d =w call $method_0x%08x()\n", ++tmp,
                instr->operand.value.token);
        break;

      case FRUITY_JUMP:
        if (instr->operand.value.target) {
          fprintf(out, "    jmp @bb%u\n",
                  instr->operand.value.target->block_id);
        }
        break;

      case FRUITY_BTRUE:
        if (instr->operand.value.target && bb->next) {
          fprintf(out, "    jnz %%t%d, @bb%u, @bb%u\n", tmp--,
                  instr->operand.value.target->block_id, bb->next->block_id);
        }
        break;

      case FRUITY_BFALSE:
        if (instr->operand.value.target && bb->next) {
          fprintf(out, "    jnz %%t%d, @bb%u, @bb%u\n", tmp--,
                  bb->next->block_id, instr->operand.value.target->block_id);
        }
        break;

      case FRUITY_RET:
        if (tmp > 0) {
          fprintf(out, "    ret %%t%d\n", tmp);
        } else {
          fprintf(out, "    ret 0\n");
        }
        break;

      case FRUITY_LIME:
        fprintf(out, "    %%ptr%d =l call $lux_alloc(w %%t%d, w 0)\n", tmp,
                tmp);
        break;

      default:
        fprintf(out, "    # opcode %d (unimplemented)\n", instr->opcode);
        break;
      }
    }
  }

  /* Ensure function ends with ret */
  fprintf(out, "    ret 0\n");
  fprintf(out, "}\n\n");

  return 0;
}

/* Compile entire assembly */
static int compile_assembly(lux9cc_options_t *opts, il_assembly_t *assembly) {
  FILE *out;
  il_method_t *method;
  fruity_function_t *func;
  il_to_fruity_error_t err;
  int method_count = 0;

  /* Open output file */
  if (strcmp(opts->output_file, "-") == 0) {
    out = stdout;
  } else {
    out = fopen(opts->output_file, "w");
    if (!out) {
      fprintf(stderr, "Error: Cannot open output file: %s\n",
              opts->output_file);
      return -1;
    }
  }

  /* Emit header */
  if (opts->format == OUTPUT_QBE) {
    emit_qbe_header(out);
  }

  /* Get entry point */
  if (assembly->cli_header.entry_point_token != 0) {
    method = il_get_method_by_token(assembly,
                                    assembly->cli_header.entry_point_token);
    if (method) {
      if (opts->verbose) {
        fprintf(stderr, "Entry point: %s (0x%08x)\n",
                method->name ? method->name : "(null)",
                assembly->cli_header.entry_point_token);
      }

      if (opts->dump_il) {
        printf("=== IL Disassembly: %s ===\n", method->name);
        il_disassemble_method(method);
        printf("\n");
      }

      /* Convert to Fruity IR */
      func = il_to_fruity_convert_method(assembly, method, &err);
      if (func) {
        if (opts->dump_ir) {
          printf("=== Fruity IR: %s ===\n", func->name);
          /* Print IR (simplified) */
        }

        if (opts->format == OUTPUT_QBE) {
          emit_qbe_function(out, func);
        }

        fruity_free_function(func);
        method_count++;
      } else {
        fprintf(stderr, "Warning: Failed to convert %s: %s\n",
                method->name ? method->name : "(null)",
                il_to_fruity_error_string(err));
      }

      il_free_method(method);
    }
  }

  if (opts->verbose) {
    fprintf(stderr, "Compiled %d method(s)\n", method_count);
  }

  /* Emit main wrapper for entry point */
  if (opts->format == OUTPUT_QBE && method_count > 0) {
    fprintf(out, "# Entry point wrapper\n");
    fprintf(out, "export function w $main() {\n");
    fprintf(out, "@start\n");
    fprintf(out, "    %%r =w call $main()\n");
    fprintf(out, "    ret %%r\n");
    fprintf(out, "}\n");
  }

  if (out != stdout) {
    fclose(out);
  }

  /* If output is .s or .o, invoke QBE */
  if (opts->format == OUTPUT_ASM || opts->format == OUTPUT_OBJ) {
    char cmd[1024];
    const char *qbe_out = opts->output_file;

    /* Generate QBE IL first */
    char qbe_tmp[] = "/tmp/lux9cc_XXXXXX.qbe";
    int fd = mkstemps(qbe_tmp, 4);
    if (fd < 0) {
      fprintf(stderr, "Error: Cannot create temp file\n");
      return -1;
    }
    close(fd);

    /* Re-run with QBE output to temp */
    lux9cc_options_t tmp_opts = *opts;
    tmp_opts.format = OUTPUT_QBE;
    tmp_opts.output_file = qbe_tmp;
    compile_assembly(&tmp_opts, assembly);

    /* Invoke QBE */
    if (opts->format == OUTPUT_ASM) {
      snprintf(cmd, sizeof(cmd), "qbe -o %s %s", qbe_out, qbe_tmp);
    } else {
      snprintf(cmd, sizeof(cmd), "qbe %s | as -o %s -", qbe_tmp, qbe_out);
    }

    if (opts->verbose) {
      fprintf(stderr, "Running: %s\n", cmd);
    }

    int ret = system(cmd);
    unlink(qbe_tmp);

    if (ret != 0) {
      fprintf(stderr, "Error: QBE compilation failed\n");
      return -1;
    }
  }

  return 0;
}

/* Detect output format from filename extension */
static output_format_t detect_format(const char *filename) {
  const char *ext = strrchr(filename, '.');
  if (!ext)
    return OUTPUT_QBE;

  if (strcmp(ext, ".qbe") == 0)
    return OUTPUT_QBE;
  if (strcmp(ext, ".s") == 0)
    return OUTPUT_ASM;
  if (strcmp(ext, ".o") == 0)
    return OUTPUT_OBJ;
  if (strcmp(ext, ".ir") == 0)
    return OUTPUT_IR;

  return OUTPUT_QBE;
}

static void print_usage(const char *prog) {
  printf("Usage: %s [options] <input.dll>\n\n", prog);
  printf("Options:\n");
  printf("  -o <file>     Output file (default: stdout)\n");
  printf("  -f <format>   Output format: qbe, asm, obj (default: auto)\n");
  printf("  -e <name>     Entry point method name\n");
  printf("  -v            Verbose output\n");
  printf("  --dump-il     Dump IL disassembly\n");
  printf("  --dump-ir     Dump Fruity IR\n");
  printf("  -h, --help    Show this help\n");
  printf("  --version     Show version\n");
  printf("\n");
  printf("Examples:\n");
  printf("  %s hello.dll -o hello.qbe     # Emit QBE IL\n", prog);
  printf("  %s hello.dll -o hello.s       # Emit x86-64 assembly\n", prog);
  printf("  %s hello.dll -o hello.o       # Emit object file\n", prog);
  printf("\n");
}

static void print_version(void) {
  printf("lux9cc %s - Lux9 .NET AOT Compiler\n", LUX9CC_VERSION);
  printf("Target: %s\n", LUX9CC_TARGET);
  printf("Pipeline: .NET IL → Fruity IR → QBE IL → Native\n");
}

int main(int argc, char **argv) {
  lux9cc_options_t opts = {0};
  opts.output_file = "-";
  opts.format = OUTPUT_QBE;

  static struct option long_opts[] = {{"help", no_argument, 0, 'h'},
                                      {"version", no_argument, 0, 'V'},
                                      {"dump-il", no_argument, 0, 'I'},
                                      {"dump-ir", no_argument, 0, 'R'},
                                      {0, 0, 0, 0}};

  int opt;
  while ((opt = getopt_long(argc, argv, "o:f:e:vh", long_opts, NULL)) != -1) {
    switch (opt) {
    case 'o':
      opts.output_file = optarg;
      opts.format = detect_format(optarg);
      break;
    case 'f':
      if (strcmp(optarg, "qbe") == 0)
        opts.format = OUTPUT_QBE;
      else if (strcmp(optarg, "asm") == 0)
        opts.format = OUTPUT_ASM;
      else if (strcmp(optarg, "obj") == 0)
        opts.format = OUTPUT_OBJ;
      else if (strcmp(optarg, "ir") == 0)
        opts.format = OUTPUT_IR;
      else {
        fprintf(stderr, "Unknown format: %s\n", optarg);
        return 1;
      }
      break;
    case 'e':
      opts.entry_point = optarg;
      break;
    case 'v':
      opts.verbose = 1;
      break;
    case 'I':
      opts.dump_il = 1;
      break;
    case 'R':
      opts.dump_ir = 1;
      break;
    case 'V':
      print_version();
      return 0;
    case 'h':
    default:
      print_usage(argv[0]);
      return opt == 'h' ? 0 : 1;
    }
  }

  if (optind >= argc) {
    fprintf(stderr, "Error: No input file specified\n");
    print_usage(argv[0]);
    return 1;
  }

  opts.input_file = argv[optind];

  /* Parse assembly */
  if (opts.verbose) {
    fprintf(stderr, "Parsing: %s\n", opts.input_file);
  }

  il_error_t err;
  il_assembly_t *assembly = il_parse_assembly(opts.input_file, &err);
  if (!assembly) {
    fprintf(stderr, "Error: Failed to parse assembly: %s\n",
            il_error_string(err));
    return 1;
  }

  if (opts.verbose) {
    fprintf(stderr, "PE sections: %u\n", assembly->section_count);
    fprintf(stderr, "CLI version: %u.%u\n",
            assembly->cli_header.major_runtime_version,
            assembly->cli_header.minor_runtime_version);
    fprintf(stderr, "Entry point: 0x%08x\n",
            assembly->cli_header.entry_point_token);
  }

  /* Compile */
  int ret = compile_assembly(&opts, assembly);

  /* Cleanup */
  il_free_assembly(assembly);

  if (ret == 0 && opts.verbose) {
    fprintf(stderr, "Output: %s\n", opts.output_file);
  }

  return ret;
}
